using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.Rendering;

public class ObjectGrabber : MonoBehaviour
{
    [Header("Physics")]
#pragma warning disable 0414
    [Tooltip("Spring strength pulling the object toward the cursor.")]
    [SerializeField] private float grabSpring = 120f;

    [Tooltip("Damper opposing overshoot.")]
    [SerializeField] private float grabDamper = 18f;

    [Tooltip("Maximum acceleration applied to the grabbed object.")]
    [SerializeField] private float maxAccel = 60f;

    [Tooltip("Maximum speed cap to prevent tunneling.")]
    [SerializeField] private float maxSpeed = 12f;
#pragma warning restore 0414

    // ── Grab feel presets (switchable at runtime via F3 debug panel) ──
    public enum GrabFeel
    {
        Default,   // current — snappy, direct
        Plucky,    // resistant tug, bouncy release — leaf-pulling feel
        Floaty,    // slow, dreamy, drifty — underwater feel
        Snappy,    // instant, no lag — arcade feel
        Heavy,     // sluggish, weighty — moving furniture feel
    }

    private static GrabFeel s_currentFeel = GrabFeel.Default;
    public static GrabFeel CurrentFeel
    {
        get => s_currentFeel;
        set
        {
            s_currentFeel = value;
            Debug.Log($"[ObjectGrabber] Grab feel: {value}");
        }
    }

    public static void CycleGrabFeel()
    {
        var values = System.Enum.GetValues(typeof(GrabFeel));
        int next = ((int)s_currentFeel + 1) % values.Length;
        CurrentFeel = (GrabFeel)next;
    }

    // Preset tuning values: spring, damper, maxAccel, maxSpeed
    private static readonly (float spring, float damper, float accel, float speed)[] s_feelPresets =
    {
        (120f, 18f, 60f,  12f),  // Default — snappy, direct
        (35f,  6f,  20f,  5f),   // Plucky — low spring, low damper = stretchy tug + overshoot bounce
        (25f,  12f, 15f,  4f),   // Floaty — low spring, high damper = slow drift, no bounce
        (500f, 40f, 200f, 25f),  // Snappy — very stiff, instant follow
        (50f,  25f, 25f,  3f),   // Heavy — medium spring, high damper, low speed cap
    };

    // Runtime overrides (driven by debug sliders, -1 = use preset)
    private static float s_overrideSpring = -1f;
    private static float s_overrideDamper = -1f;
    private static float s_overrideAccel = -1f;
    private static float s_overrideSpeed = -1f;

    public static void SetGrabOverrides(float spring, float damper, float accel, float speed)
    {
        s_overrideSpring = spring;
        s_overrideDamper = damper;
        s_overrideAccel = accel;
        s_overrideSpeed = speed;
    }

    public static void GetCurrentGrabParams(out float spring, out float damper, out float accel, out float speed)
    {
        if (s_overrideSpring > 0f)
        {
            spring = s_overrideSpring; damper = s_overrideDamper;
            accel = s_overrideAccel; speed = s_overrideSpeed;
            return;
        }
        var p = s_feelPresets[(int)s_currentFeel];
        spring = p.spring; damper = p.damper; accel = p.accel; speed = p.speed;
    }

    private void GetActiveGrabParams(out float spring, out float damper, out float accel, out float speed)
    {
        if (s_overrideSpring > 0f)
        {
            spring = s_overrideSpring;
            damper = s_overrideDamper;
            accel = s_overrideAccel;
            speed = s_overrideSpeed;
            return;
        }
        var p = s_feelPresets[(int)s_currentFeel];
        spring = p.spring;
        damper = p.damper;
        accel = p.accel;
        speed = p.speed;
    }

    [Header("Grid Snap")]
    [Tooltip("Grid cell size in world units. Placement is always grid-snapped — no toggle.")]
    [SerializeField] private float gridSize = 0.03f;

    public float GridSize
    {
        get => gridSize;
        set => gridSize = Mathf.Max(0.01f, value);
    }

    /// <summary>Global grid cell size, set in Awake. PlaceableObject reads this on Start to snap scene-placed items.</summary>
    public static float GlobalGridSize { get; private set; } = 0.03f;

    [Header("Scroll Behavior")]
    [Tooltip("Degrees rotated per scroll tick around Y axis.")]
    [SerializeField] private float scrollRotateStep = 45f;

    [Header("Raycast")]
    [Tooltip("Layer mask for placeable objects.")]
    [SerializeField] private LayerMask placeableLayer = ~0;

    [Tooltip("Layer mask for surface triggers (auto-generated by PlacementSurface).")]
    [SerializeField] private LayerMask surfaceLayer;

    [Tooltip("Camera used for raycasting. Auto-finds MainCamera if null.")]
    [SerializeField] private Camera cam;

    [Tooltip("Layer mask for wall/ceiling/floor geometry that held items cannot pass through.")]
    [SerializeField] private LayerMask _wallLayer = 1; // Default layer

    [Tooltip("Additional layer mask for barriers (closed cubbies, custom blockers). Merged with _wallLayer for clamping.")]
    [SerializeField] private LayerMask _barrierLayer;

    [Header("Audio")]
    [Tooltip("SFX played when picking up an object.")]
    [SerializeField] private AudioClip _pickupSFX;

    [Tooltip("SFX played when placing an object on a surface.")]
    [SerializeField] private AudioClip _placeSFX;

    [Header("Tether")]
    [Tooltip("Max distance between grab target and held object before teleporting to catch up.")]
    [SerializeField] private float maxTetherDistance = 3f;

    // Input managed by IrisInput singleton

    private bool _isEnabled;

    /// <summary>Fired after an object is placed on a surface. Arg: the placed object.</summary>
    public static event System.Action<PlaceableObject> OnObjectPlaced;

    private static ObjectGrabber s_instance;

    /// <summary>True when any ObjectGrabber is holding an object. Check this to block other interactions.</summary>
    public static bool IsHoldingObject => s_instance != null && s_instance._held != null;

    /// <summary>The currently held PlaceableObject, or null if nothing is held.</summary>
    public static PlaceableObject HeldObject => s_instance != null ? s_instance._held : null;

    /// <summary>The surface the held object is currently hovering over, or null.</summary>
    public static PlacementSurface CurrentSurface => s_instance != null ? s_instance._currentSurface : null;

    /// <summary>
    /// True when ObjectGrabber consumed a click this frame (picked up, placed, toggled drawer/switch).
    /// Other click-driven systems should check this to avoid processing the same click.
    /// </summary>
    public static bool ClickConsumedThisFrame { get; private set; }
    private static int s_lastConsumedFrame = -1;

    /// <summary>Force-release the held item without placing. Used by FridgeController deposit.</summary>
    public static void ForceReleaseHeld()
    {
        if (s_instance != null && s_instance._held != null)
            s_instance.ClearHeld();
    }

    private PlaceableObject _held;
    private Rigidbody _heldRb;
    private Vector3 _grabTarget;
    private float _fallbackDepth;
    private RigidbodyConstraints _originalConstraints;
    private float _heldShadowDiameter;
    private Vector3 _heldBoundsExtents;

    // Pickup feel: plucky spring on pickup, then ramp to stiff carry
    private float _pickupTimer;
    private const float PickupFeelDuration = 0.25f; // seconds of plucky feel after pickup

    // Surface tracking
    private PlacementSurface _currentSurface;
    private PlacementSurface _lastValidSurface;
    private float _wallRotation;
    private bool _isOnWall;

    // Double-click detection for plate unstacking
    private float _lastClickTime;
    private const float DoubleClickThreshold = 0.3f;

    // Shadow preview
    private GameObject _shadowGO;
    private MeshRenderer _shadowRenderer;
    private Material _shadowMat;
    private static readonly Color s_shadowValid = new Color(0.25f, 0.9f, 0.3f, 0.75f);
    private static readonly Color s_shadowInvalid = new Color(0.95f, 0.18f, 0.2f, 0.75f);

    // Ghost preview (translucent copy of the held item at the snapped grid cell)
    [Header("Ghost Preview")]
    [Tooltip("If true, a translucent duplicate of the held item is shown at the grid-snapped cell so the player sees exactly where it will land. Works alongside the disc shadow.")]
    [SerializeField] private bool _useGhostPreview = true;
    [Tooltip("Tint applied to the ghost preview. Alpha controls see-through amount.")]
    [SerializeField] private Color _ghostTint = new Color(0.5f, 0.95f, 0.55f, 0.35f);
    private GameObject _ghostPreviewGO;
    private readonly List<Material> _ghostPreviewMats = new();

    private void Awake()
    {
        s_instance = this;
        GlobalGridSize = gridSize;

        if (cam == null)
            cam = Camera.main;

        // Load default click SFX from Resources if none assigned in Inspector
        if (_pickupSFX == null)
            _pickupSFX = Resources.Load<AudioClip>("Audio/default_click");
        if (_placeSFX == null)
            _placeSFX = Resources.Load<AudioClip>("Audio/default_click");

        BuildShadow();
    }

    // Input managed by IrisInput singleton — no local enable/disable needed.

    private void OnDestroy()
    {
        if (s_instance == this) s_instance = null;
        if (_shadowMat != null) Destroy(_shadowMat);
        DestroyGhostPreview();
    }

    private void Update()
    {
        if (DayPhaseManager.Instance != null && !DayPhaseManager.Instance.IsInteractionPhase)
            return;

        if (!_isEnabled) return;

        // Reset click consumption flag at start of each frame
        if (Time.frameCount != s_lastConsumedFrame)
            ClickConsumedThisFrame = false;

        if (IrisInput.Instance != null && IrisInput.Instance.Click.WasPressedThisFrame())
        {
            // Block game-world clicks when pointer is over UI
            if (EventSystem.current != null && EventSystem.current.IsPointerOverGameObject())
                return;

            if (_held == null)
            {
                TryPickUp();
            }
            else
            {
                // Double-click while holding a plate stack → unstack top plate
                float now = Time.unscaledTime;
                bool isDoubleClick = (now - _lastClickTime) < DoubleClickThreshold;
                _lastClickTime = now;

                if (isDoubleClick && TryUnstackHeldPlate())
                {
                    ConsumeClick();
                    return;
                }

                // If holding a pairable item, check if clicking its match → snap pair.
                // This is the ONLY path for placing one item on top of another —
                // non-pairable items can't be stacked.
                if (TryPairWithClicked())
                {
                    ConsumeClick();
                    return;
                }

                Place();
                ConsumeClick();
            }
        }

        if (_held != null)
        {
            UpdateGrabTarget();
            UpdateScrollInput();
            UpdateShadow();
        }
    }

    private void FixedUpdate()
    {
        if (_held == null || _heldRb == null) return;

        // Tether snap-back
        if (Vector3.Distance(_heldRb.position, _grabTarget) > maxTetherDistance)
        {
            _heldRb.position = _grabTarget;
            _heldRb.linearVelocity = Vector3.zero;
        }

        // Pickup feel: plucky spring for the first fraction of a second,
        // then ramp to stiff carry so the object follows smoothly.
        _pickupTimer = Mathf.Max(_pickupTimer - Time.fixedDeltaTime, 0f);
        float pickupT = Mathf.Clamp01(_pickupTimer / PickupFeelDuration); // 1 = just picked up, 0 = carrying

        GetActiveGrabParams(out float presetSpring, out float presetDamper,
            out float presetAccel, out float presetSpeed);

        // Carry params: stiff, direct follow
        const float carrySpring = 400f;
        const float carryDamper = 35f;
        const float carryAccel = 150f;
        const float carrySpeed = 20f;

        // Blend from preset (plucky) to carry (stiff)
        float activeSpring = Mathf.Lerp(carrySpring, presetSpring, pickupT);
        float activeDamper = Mathf.Lerp(carryDamper, presetDamper, pickupT);
        float activeMaxAccel = Mathf.Lerp(carryAccel, presetAccel, pickupT);
        float activeMaxSpeed = Mathf.Lerp(carrySpeed, presetSpeed, pickupT);

        Vector3 toTarget = _grabTarget - _heldRb.worldCenterOfMass;
        Vector3 force = toTarget * activeSpring - _heldRb.linearVelocity * activeDamper;

        if (force.sqrMagnitude > activeMaxAccel * activeMaxAccel)
            force = force.normalized * activeMaxAccel;

        _heldRb.AddForce(force, ForceMode.Acceleration);

        // Speed cap
        if (_heldRb.linearVelocity.sqrMagnitude > activeMaxSpeed * activeMaxSpeed)
            _heldRb.linearVelocity = _heldRb.linearVelocity.normalized * activeMaxSpeed;
    }

    // ── Pick up ──────────────────────────────────────────────────────

    private static void ConsumeClick()
    {
        ClickConsumedThisFrame = true;
        s_lastConsumedFrame = Time.frameCount;
    }

    /// <summary>Allow other systems (WateringManager, CleaningManager) to consume the click.</summary>
    public static void ConsumeClickExternal() => ConsumeClick();

    private void TryPickUp()
    {
        Vector2 screenPos = IrisInput.CursorPosition;
        Ray ray = cam.ScreenPointToRay(screenPos);

        if (!Physics.Raycast(ray, out RaycastHit hit, 100f, placeableLayer))
            return;

        var placeable = hit.collider.GetComponent<PlaceableObject>();
        if (placeable == null)
            placeable = hit.collider.GetComponentInParent<PlaceableObject>();

        // No placeable hit — check for cubby/drawer door click
        if (placeable == null)
        {
            var clickedDrawer = hit.collider.GetComponent<DrawerController>();
            if (clickedDrawer == null)
                clickedDrawer = hit.collider.GetComponentInParent<DrawerController>();

            if (clickedDrawer != null)
            {
                if (clickedDrawer.CurrentState == DrawerController.State.Closed)
                    clickedDrawer.Open();
                else if (clickedDrawer.CurrentState == DrawerController.State.Open)
                    clickedDrawer.Close();
                ConsumeClick();
                return;
            }

            // Check for Nema click — open personality/wellbeing panel (non-date only)
            var nema = hit.collider.GetComponent<NemaController>();
            if (nema == null) nema = hit.collider.GetComponentInParent<NemaController>();
            if (nema != null)
            {
                if (DayPhaseManager.Instance == null
                    || DayPhaseManager.Instance.CurrentPhase != DayPhaseManager.DayPhase.DateInProgress)
                {
                    NemaProfilePanel.Instance?.Open();
                    ConsumeClick();
                    return;
                }
            }

            // Check for light switch click
            var lightSwitch = hit.collider.GetComponent<LightSwitch>();
            if (lightSwitch == null)
                lightSwitch = hit.collider.GetComponentInParent<LightSwitch>();
            if (lightSwitch != null)
            {
                lightSwitch.Toggle();
                ConsumeClick();
                return;
            }

            // Check for turntable click — eject record
            var clickedSlot = hit.collider.GetComponent<RecordSlot>();
            if (clickedSlot == null)
                clickedSlot = hit.collider.GetComponentInParent<RecordSlot>();
            if (clickedSlot != null && clickedSlot.IsPlaying)
            {
                clickedSlot.EjectRecord();
                ConsumeClick();
                return;
            }

            return;
        }

        if (placeable.CurrentState == PlaceableObject.State.Held)
            return;

        // Records use click-to-select — no physical grab
        var recordItem = placeable.GetComponent<RecordItem>();
        if (recordItem != null)
        {
            recordItem.SelectForPlayback();
            ConsumeClick();
            return;
        }

        ConsumeClick();
        _held = placeable;
        _pickupTimer = PickupFeelDuration;

        // Flash partner highlight for pairable items (shoes)
        var pairable = placeable.GetComponent<PairableItem>();
        if (pairable != null) pairable.OnPickedUp();

        // Cache collider bounds BEFORE disabling — used for shadow size + surface offset
        var pickupCol = placeable.GetComponent<Collider>();
        if (pickupCol != null)
        {
            _heldBoundsExtents = pickupCol.bounds.extents;
            _heldShadowDiameter = Mathf.Max(_heldBoundsExtents.x, _heldBoundsExtents.z) * 2f * 1.3f;
        }
        else
        {
            _heldBoundsExtents = Vector3.one * 0.1f;
            _heldShadowDiameter = 0.3f;
        }

        // Detach from plate stack before pickup
        var stackable = placeable.GetComponent<StackablePlate>();
        if (stackable != null)
            stackable.PrepareForGrab();

        _heldRb = placeable.GetComponent<Rigidbody>();
        _heldRb.useGravity = false;
        _heldRb.isKinematic = false;
        _heldRb.collisionDetectionMode = CollisionDetectionMode.ContinuousDynamic;
        _grabTarget = _heldRb.worldCenterOfMass;

        // Store depth for floating fallback when cursor isn't over a surface
        _fallbackDepth = Vector3.Dot(
            _heldRb.worldCenterOfMass - cam.transform.position,
            cam.transform.forward);

        // Lock rotation so collisions don't spin the object
        _originalConstraints = _heldRb.constraints;
        _heldRb.constraints = _originalConstraints | RigidbodyConstraints.FreezeRotation;

        _currentSurface = placeable.LastPlacedSurface;
        _lastValidSurface = _currentSurface;
        _wallRotation = 0f;
        _isOnWall = false;

        placeable.OnPickedUp();

        // Keep interactable highlight while held
        var heldHL = placeable.GetComponent<InteractableHighlight>();
        if (heldHL != null)
        {
            heldHL.SetHighlighted(true);
            heldHL.SetInteractHighlighted(true);
        }

        // Book hidden item check
        var bookItem = placeable.GetComponent<BookItem>();
        if (bookItem != null) bookItem.OnBookPickedUp();

        AudioManager.Instance?.PlaySFX(placeable.PickupSFXOverride != null ? placeable.PickupSFXOverride : _pickupSFX);
        ShowShadow(true);
        BuildGhostPreview(placeable);

        // Show pickup description
        if (PickupDescriptionHUD.Instance != null)
            PickupDescriptionHUD.Instance.Show(placeable.ItemDescription);
    }

    // ── Place ────────────────────────────────────────────────────────

    private void Place()
    {
        if (_held == null) return;

        // ── DiscoBall check ──
        if (_currentSurface != null)
        {
            var disco = _currentSurface.GetComponentInParent<DiscoBallController>();
            if (disco != null && _held.GetComponent<DiscoBallBulb>() != null)
            {
                _heldRb.constraints = _originalConstraints;
                _heldRb.linearVelocity = Vector3.zero;
                if (disco.TryAcceptBulb(_held))
                {
                    PlayPlaceSFX(_held);
                    ClearHeld();
                    return;
                }
            }
        }

        // Check if clicking directly on a DropZone (trash can body, fridge, etc.)
        // This runs regardless of surface state so clicking anywhere on the
        // trash can (body or lid) deposits trash.
        if (TryDepositAtNearbyZone())
        {
            ConsumeClick();
            return;
        }

        // No surface — nothing more to do
        if (_currentSurface == null) return;

        // ── DropZone check ──
        // Only match the DropZone directly on this surface — parent/child
        // traversal was causing the kitchen counter to match the nearby sink.
        {
            DropZone zone = _currentSurface.GetComponent<DropZone>();

            // Proximity fallback for non-destroy zones only (shoe rack, etc.).
            // Destroy zones (sink, trash can) must be placed directly on a
            // surface to match — otherwise adjacent surfaces steal deposits.
            if (zone == null)
            {
                float bestDist = float.MaxValue;
                var allZones = DropZone.All;
                for (int i = 0; i < allZones.Count; i++)
                {
                    var z = allZones[i];
                    if (z == null) continue;
                    if (z.DestroyOnDeposit) continue; // skip sink/trash — direct match only

                    float dist = Vector3.Distance(z.transform.position, _grabTarget);
                    if (dist < 2f && dist < bestDist)
                    {
                        bestDist = dist;
                        zone = z;
                    }
                }
            }

            if (zone != null)
            {
                bool matchesHome = (!string.IsNullOrEmpty(_held.HomeZoneName) && zone.ZoneName == _held.HomeZoneName)
                    || (!string.IsNullOrEmpty(_held.AltHomeZoneName) && zone.ZoneName == _held.AltHomeZoneName);
                // Category-specific destroy zones (trash→TrashCan, dishes→Sink, milk→Fridge)
                if (!matchesHome && zone.DestroyOnDeposit)
                {
                    if (_held.Category == ItemCategory.Trash && zone.ZoneName == "TrashCan")
                        matchesHome = true;
                    else if (_held.Category == ItemCategory.Dish && zone.ZoneName == "Sink")
                        matchesHome = true;
                }
                // Shoes must be paired before placing at their home station
                if (matchesHome)
                {
                    var pairable = _held.GetComponent<PairableItem>();
                    if (pairable != null && pairable.Mode == PairableItem.PairMode.SpecificPartner && !pairable.IsPaired)
                    {
                        Debug.Log("[ObjectGrabber] Shoe must be paired before placing at station.");
                        return; // block placement
                    }
                }

                if (matchesHome)
                {
                    _heldRb.constraints = _originalConstraints;
                    _heldRb.linearVelocity = Vector3.zero;

                    if (zone.DestroyOnDeposit)
                    {
                        // Trash can — shrink and destroy
                        zone.RegisterDeposit(_held);
                        ClearHeld();
                        return;
                    }

                    // Auto-slot deposit (shoe rack, etc.) — snap to the next
                    // free slot in a row instead of dropping at the cursor.
                    if (zone.UseSlotting
                        && zone.TryGetNextDepositSlot(out var slotPos, out var slotRot))
                    {
                        _held.OnPlaced(_currentSurface, true, slotPos, slotRot);

                        // Lock slotted items in place — they shouldn't fall off
                        // their slot or roll around. Picking the shoe back up
                        // re-enables physics via PlaceableObject.OnPickedUp.
                        LockRigidbodyAtSlot(_held);

                        zone.RegisterDeposit(_held);
                        OnObjectPlaced?.Invoke(_held);
                        PlayPlaceSFX(_held);
                        ClearHeld();
                        return;
                    }

                    // Normal drop zone — place normally, zone registers deposit
                    // Fall through to standard placement, OnPlaced will set IsAtHome
                }
            }
        }

        // Wall items only on walls, table items only on tables
        if (_currentSurface.IsVertical && !_held.CanWallMount)
        {
            Debug.Log($"[ObjectGrabber] BLOCKED: surface '{_currentSurface.name}' IsVertical={_currentSurface.IsVertical} but item CanWallMount=false");
            return;
        }
        if (!_currentSurface.IsVertical && _held.WallOnly)
        {
            Debug.Log($"[ObjectGrabber] BLOCKED: surface '{_currentSurface.name}' is horizontal but item is WallOnly");
            return;
        }

        // Trash only on floor or trash cans
        if (_held.Category == ItemCategory.Trash)
        {
            var zone = _currentSurface.GetComponent<DropZone>();
            bool isTrashCan = zone != null && zone.DestroyOnDeposit;
            if (!_currentSurface.IsFloor && !isTrashCan)
            {
                Debug.Log($"[ObjectGrabber] BLOCKED TRASH: surface '{_currentSurface.name}' IsFloor={_currentSurface.IsFloor} isTrashCan={isTrashCan}");
                return;
            }
        }

        // Use _grabTarget (cursor-tracked) instead of _heldRb.position for wall face
        // detection — the rigidbody can overshoot through thin wall triggers.
        var hitResult = _currentSurface.ProjectOntoSurface(_grabTarget, cam.transform.position);
        Vector3 pos = _currentSurface.SnapToGrid(hitResult.worldPosition, gridSize, cam.transform.position);

        float halfExtent = GetHeldHalfExtentAlongNormal(hitResult.surfaceNormal);
        pos += hitResult.surfaceNormal * halfExtent;

        Quaternion rot;
        if (_currentSurface.IsVertical)
        {
            rot = Quaternion.LookRotation(hitResult.surfaceNormal, Vector3.up)
                * Quaternion.AngleAxis(_wallRotation, Vector3.forward);
        }
        else
        {
            rot = _held.transform.rotation;
        }

        // Home snap: if placing near the item's home position, use exact home pos/rot
        if (_held.HasHome && Vector3.Distance(pos, _held.HomePosition) < _held.HomeTolerance * 2f)
        {
            pos = _held.HomePosition;
            rot = _held.HomeRotation;
        }

        // Cubby capacity check — reject placement if cubby is full
        var capacityCubby = DrawerController.FindByInteriorSurface(_currentSurface);
        if (capacityCubby != null && !capacityCubby.HasInteriorCapacity)
        {
            if (DialoguePortraitBox.Instance != null)
                DialoguePortraitBox.Instance.Say("No room in here.", 2f);
            else
                PickupDescriptionHUD.Instance?.Show("No room in here.");
            return;
        }

        // Occupancy check — block placement if another item already occupies the
        // resolved cell. Pairables stack via the click-on-partner path
        // (TryPairWithClicked above); plain placement here is never allowed to
        // overlap a sibling.
        if (FindOccupant(pos) != null)
        {
            Debug.Log($"[ObjectGrabber] BLOCKED: cell occupied at {pos}");
            return;
        }

        // Restore constraints before placement configures the rigidbody
        _heldRb.constraints = _originalConstraints;
        _heldRb.linearVelocity = Vector3.zero;

        _held.OnPlaced(_currentSurface, true, pos, rot);

        // Book public/private toggle based on placement surface
        var bookItem = _held.GetComponent<BookItem>();
        if (bookItem != null) bookItem.OnBookPlaced(_currentSurface);

        // Cubby privacy: items placed on a closed cubby's interior surface become private.
        // Items placed anywhere else become public (clears stale privacy from previous location).
        var cubbyDrawer = DrawerController.FindByInteriorSurface(_currentSurface);
        bool inClosedCubby = cubbyDrawer != null && cubbyDrawer.IsInteriorAndClosed(_currentSurface);
        var privTag = _held.GetComponent<ReactableTag>();
        if (privTag != null)
            privTag.IsPrivate = inClosedCubby;

        OnObjectPlaced?.Invoke(_held);
        PlayPlaceSFX(_held);

        // DropZone deposit (non-destroy — item stays placed on surface)
        {
            var zone = _currentSurface.GetComponent<DropZone>();
            if (zone != null)
            {
                bool match = (!string.IsNullOrEmpty(_held.HomeZoneName) && zone.ZoneName == _held.HomeZoneName)
                    || (!string.IsNullOrEmpty(_held.AltHomeZoneName) && zone.ZoneName == _held.AltHomeZoneName);
                if (match)
                    zone.RegisterDeposit(_held);
            }
        }

        // Stack-aware plate hooks. No more auto-stack-on-place: stacking only
        // happens through explicit pairable click (TryPairWithClicked above).
        var stackable = _held.GetComponent<StackablePlate>();
        if (stackable != null)
        {
            var dishZone = _currentSurface != null
                ? _currentSurface.GetComponent<DishDropZone>() : null;
            if (dishZone != null)
            {
                // Deposit the held plate plus any child plates in the stack
                dishZone.RegisterDeposit(stackable);
                var childPlates = stackable.GetComponentsInChildren<StackablePlate>();
                foreach (var child in childPlates)
                {
                    if (child != stackable)
                        dishZone.RegisterDeposit(child);
                }
            }
        }

        ClearHeld();
    }

    // ── Pair / stacking helpers ─────────────────────────────────────

    // Forgiving radius for pairing/stacking — SphereCast instead of Raycast
    private const float PairStackRadius = 0.08f;

    [Header("Pair Snap")]
    [Tooltip("World-space radius at which the held item magnetically snaps toward its pair partner while carrying.")]
    [SerializeField] private float _pairSnapRadius = 0.4f;

    private bool TryPairWithClicked()
    {
        if (_held == null) return false;

        var heldPairable = _held.GetComponent<PairableItem>();
        if (heldPairable == null) return false;
        // SpecificPartner (shoes) can't re-pair, but AnyOfCategory (plates) can stack freely
        if (heldPairable.IsPaired && heldPairable.Mode == PairableItem.PairMode.SpecificPartner) return false;

        Vector2 screenPos = IrisInput.CursorPosition;
        Ray ray = cam.ScreenPointToRay(screenPos);

        // Use SphereCast for forgiving click area, fall back to RaycastAll
        PairableItem clickedPairable = FindComponentAlongRay<PairableItem>(ray, placeableLayer);

        // If precise click missed, accept the snap target we're already locked onto
        if ((clickedPairable == null || clickedPairable == heldPairable || !clickedPairable.CanPairWith(heldPairable))
            && _pairSnapTarget != null && _pairSnapTarget.CanPairWith(heldPairable))
        {
            clickedPairable = _pairSnapTarget;
        }

        if (clickedPairable == null || clickedPairable == heldPairable) return false;
        if (!clickedPairable.CanPairWith(heldPairable)) return false;

        // Release held item from grabber
        _heldRb.constraints = _originalConstraints;
        _heldRb.linearVelocity = Vector3.zero;

        // Clean up held item visuals before pairing
        _held.ForceRestoreMaterial();
        _held.ForceDestroySilhouette();

        // Snap pair
        clickedPairable.SnapPair(heldPairable);

        PlayPlaceSFX(_held);
        ClearHeld();
        return true;
    }

    // ── Pair snap (magnetic carry bias) ──────────────────────────────

    private PairableItem _pairSnapTarget; // currently snapped-to partner (null = no snap)

    /// <summary>
    /// When holding a pairable item near its partner, snap the grab target
    /// to the pair position so the item magnetically locks in place.
    /// Called from UpdateGrabTarget after the normal position is calculated.
    /// </summary>
    private void UpdatePairSnap()
    {
        _pairSnapTarget = null;
        if (_held == null) return;

        var heldPairable = _held.GetComponent<PairableItem>();
        if (heldPairable == null) return;
        if (heldPairable.IsPaired && heldPairable.Mode == PairableItem.PairMode.SpecificPartner) return;

        // Find the nearest valid partner within snap radius
        PairableItem best = null;
        float bestDist = _pairSnapRadius;

        var allItems = PlaceableObject.All;
        for (int i = 0; i < allItems.Count; i++)
        {
            var po = allItems[i];
            if (po == null || po == _held) continue;
            if (po.CurrentState == PlaceableObject.State.Held) continue;

            var pairable = po.GetComponent<PairableItem>();
            if (pairable == null || pairable == heldPairable) continue;
            if (!pairable.CanPairWith(heldPairable)) continue;

            float dist = Vector3.Distance(po.transform.position, _grabTarget);
            if (dist < bestDist)
            {
                bestDist = dist;
                best = pairable;
            }
        }

        if (best == null) return;

        _pairSnapTarget = best;

        // Calculate the position the held item would land at when paired
        Vector3 snapPos = best.GetPairSnapPosition(heldPairable);
        _grabTarget = snapPos;

        // Hard-teleport so the item locks instantly (no spring lag)
        if (_heldRb != null)
        {
            _heldRb.position = snapPos;
            _heldRb.linearVelocity = Vector3.zero;
            _heldRb.angularVelocity = Vector3.zero;
        }
    }

    /// <summary>
    /// Forgiving component search along a ray. Tries SphereCast first (wider hit area),
    /// then falls back to RaycastAll for objects the sphere might miss.
    /// </summary>
    private static T FindComponentAlongRay<T>(Ray ray, LayerMask layer) where T : Component
    {
        // 1. SphereCast — generous hit radius
        if (Physics.SphereCast(ray, PairStackRadius, out RaycastHit sphereHit, 100f, layer))
        {
            var comp = sphereHit.collider.GetComponent<T>();
            if (comp == null) comp = sphereHit.collider.GetComponentInParent<T>();
            if (comp != null) return comp;
        }

        // 2. RaycastAll — check all hits along the exact ray
        var hits = Physics.RaycastAll(ray, 100f, layer);
        float bestDist = float.MaxValue;
        T best = null;
        for (int i = 0; i < hits.Length; i++)
        {
            var comp = hits[i].collider.GetComponent<T>();
            if (comp == null) comp = hits[i].collider.GetComponentInParent<T>();
            if (comp != null && hits[i].distance < bestDist)
            {
                bestDist = hits[i].distance;
                best = comp;
            }
        }
        return best;
    }

    /// Double-click while holding a plate with children → detach the topmost child
    /// and place/drop the remaining stack.
    /// </summary>
    private bool TryUnstackHeldPlate()
    {
        var heldStack = _held.GetComponent<StackablePlate>();
        if (heldStack == null) return false;

        // Find topmost child plate
        StackablePlate topChild = null;
        foreach (Transform child in _held.transform)
        {
            var sp = child.GetComponent<StackablePlate>();
            if (sp != null)
                topChild = sp;
        }
        if (topChild == null) return false;

        // Detach the top plate — it becomes the new held object
        topChild.PrepareForGrab();

        // Drop the current stack onto the nearest surface
        _heldRb.constraints = _originalConstraints;
        _heldRb.linearVelocity = Vector3.zero;
        _heldRb.useGravity = true;
        _held.OnDropped();

        // Pick up the detached top plate
        var oldHeld = _held;
        _held = topChild.GetComponent<PlaceableObject>();
        _heldRb = topChild.GetComponent<Rigidbody>();
        if (_heldRb != null)
        {
            _heldRb.useGravity = false;
            _heldRb.isKinematic = false;
            _grabTarget = _heldRb.worldCenterOfMass;
            _originalConstraints = _heldRb.constraints;
            _heldRb.constraints = _originalConstraints | RigidbodyConstraints.FreezeRotation;
        }
        _held.OnPickedUp();

        Debug.Log($"[ObjectGrabber] Unstacked {topChild.name} from {oldHeld.name}");
        return true;
    }

    /// <summary>
    /// Try to deposit the held item at the nearest DropZone when not over a PlacementSurface.
    /// Used for fridge, trash can, etc. that don't have placement surfaces.
    /// </summary>
    private bool TryDepositAtNearbyZone()
    {
        if (_held == null) return false;

        // Raycast to see what we clicked on
        Vector2 screenPos = IrisInput.CursorPosition;
        Ray ray = cam.ScreenPointToRay(screenPos);
        if (!Physics.Raycast(ray, out RaycastHit hit, 100f)) return false;

        // Check the hit object and its parents for a DropZone
        var zone = hit.collider.GetComponent<DropZone>();
        if (zone == null) zone = hit.collider.GetComponentInParent<DropZone>();
        if (zone == null) return false;

        // Check if the held item matches this zone (name match or category match)
        bool matches = (!string.IsNullOrEmpty(_held.HomeZoneName) && zone.ZoneName == _held.HomeZoneName)
                    || (!string.IsNullOrEmpty(_held.AltHomeZoneName) && zone.ZoneName == _held.AltHomeZoneName);
        // Category-specific destroy zones: trash→TrashCan, dishes→Sink
        if (!matches && zone.DestroyOnDeposit)
        {
            if (_held.Category == ItemCategory.Trash && zone.ZoneName == "TrashCan")
                matches = true;
            else if (_held.Category == ItemCategory.Dish && zone.ZoneName == "Sink")
                matches = true;
        }
        if (!matches) return false;

        // Deposit
        _held.ForceRestoreMaterial();
        _held.ForceDestroySilhouette();
        var item = _held;
        ClearHeld();
        zone.RegisterDeposit(item);
        PlayPlaceSFX(item);
        Debug.Log($"[ObjectGrabber] Deposited {item.name} at zone '{zone.ZoneName}'");
        return true;
    }

    private void PlayPlaceSFX(PlaceableObject obj)
    {
        var clip = obj != null && obj.PlaceSFXOverride != null ? obj.PlaceSFXOverride : _placeSFX;
        AudioManager.Instance?.PlaySFX(clip);
    }

    private void ClearHeld()
    {
        // Restore discrete collision detection
        if (_heldRb != null)
            _heldRb.collisionDetectionMode = CollisionDetectionMode.Discrete;

        if (_held != null)
        {
            // Always clean up held item visuals
            _held.ForceRestoreMaterial();
            _held.ForceDestroySilhouette();

            // Stop partner highlight flash + restore partner color
            var pairable = _held.GetComponent<PairableItem>();
            if (pairable != null) pairable.OnPutDown();

            // Turn off held highlight
            var hl = _held.GetComponent<InteractableHighlight>();
            if (hl != null)
            {
                hl.SetHighlighted(false);
                hl.SetInteractHighlighted(false);
            }
        }

        _held = null;
        _heldRb = null;
        _currentSurface = null;
        _lastValidSurface = null;
        _isOnWall = false;
        _pairSnapTarget = null;
        ShowShadow(false);
        DestroyGhostPreview();

        // Safety: unlock cursor in case an interaction lock was active
        GlobalCursorManager.UnlockCursor();

        if (PickupDescriptionHUD.Instance != null)
            PickupDescriptionHUD.Instance.Hide();
    }

    // ── Grab target (surface raycast with depth-plane fallback) ──────

    private void UpdateGrabTarget()
    {
        Vector2 screenPos = IrisInput.CursorPosition;
        Ray ray = cam.ScreenPointToRay(screenPos);

        bool foundSurface = false;

        // RaycastAll so the ray can pass through nearer surfaces to reach
        // ones further away (e.g. coffee table in living room from kitchen camera).
        var hits = Physics.RaycastAll(ray, 100f, surfaceLayer);
        if (hits.Length > 0)
        {
            // Linear pass: find nearest valid surface without sorting
            float bestDist = float.MaxValue;
            int bestIndex = -1;
            PlacementSurface bestSurface = null;

            for (int h = 0; h < hits.Length; h++)
            {
                if (hits[h].distance >= bestDist) continue;
                var surface = hits[h].collider.GetComponentInParent<PlacementSurface>();
                bool surfaceValid = surface != null
                    && (!surface.IsVertical || _held.CanWallMount)
                    && (surface.IsVertical || !_held.WallOnly);
                if (!surfaceValid) continue;

                bestDist = hits[h].distance;
                bestIndex = h;
                bestSurface = surface;
            }

            if (bestIndex >= 0)
            {
                _currentSurface = bestSurface;
                _lastValidSurface = bestSurface;
                _isOnWall = bestSurface.IsVertical;

                var hitResult = bestSurface.ProjectOntoSurface(hits[bestIndex].point, cam.transform.position);
                Vector3 pos = bestSurface.SnapToGrid(hitResult.worldPosition, gridSize, cam.transform.position);

                float halfExtent = GetHeldHalfExtentAlongNormal(hitResult.surfaceNormal);
                pos += hitResult.surfaceNormal * halfExtent;

                // Heavy slot snap — if the surface has a slotted DropZone the
                // held item belongs to, override pos with the next free slot
                // and teleport the rigidbody so the shoe physically clicks in.
                var slotZone = bestSurface.GetComponent<DropZone>();
                if (slotZone == null) slotZone = bestSurface.GetComponentInParent<DropZone>();
                if (slotZone != null && slotZone.UseSlotting && _held != null
                    && (slotZone.ZoneName == _held.HomeZoneName || slotZone.ZoneName == _held.AltHomeZoneName)
                    && slotZone.TryPeekNextDepositSlot(out var slotPos, out _))
                {
                    pos = slotPos;
                    if (_heldRb != null)
                    {
                        _heldRb.position = pos;
                        _heldRb.linearVelocity = Vector3.zero;
                        _heldRb.angularVelocity = Vector3.zero;
                    }
                }

                _grabTarget = pos;

                // Track depth so fallback stays smooth if cursor leaves surface
                _fallbackDepth = Vector3.Dot(
                    _grabTarget - cam.transform.position,
                    cam.transform.forward);

                if (_isOnWall)
                    _held.AlignToWall(hitResult.surfaceNormal, _wallRotation);

                foundSurface = true;
            }
        }

        if (!foundSurface)
        {
            // No valid surface or dollying — float at fallback depth following cursor
            _currentSurface = null;
            _isOnWall = false;

            Vector3 planePoint = cam.transform.position + cam.transform.forward * _fallbackDepth;
            var plane = new Plane(-cam.transform.forward, planePoint);
            if (plane.Raycast(ray, out float enter))
                _grabTarget = ray.GetPoint(enter);
        }

        // Wall clamping removed — felt too harsh. Surface bounds still constrain placement.

        // Pair snap: if holding a pairable item near its partner, override
        // _grabTarget to magnetically lock onto the pair position.
        UpdatePairSnap();
    }

    /// <summary>
    /// Clamps _grabTarget so the held item cannot pass through walls and always
    /// stays on the camera's side of any geometry (no wall between camera and item).
    /// </summary>
    private void ClampGrabTargetToWalls()
    {
        if (_heldRb == null) return;

        const float margin = 0.05f;
        int blockMask = _wallLayer | _barrierLayer;

        // 1) Camera → target: keep item on camera's side of any wall/barrier
        //    (skip when on a surface to allow cross-room placement)
        if (_currentSurface == null)
        {
            Vector3 camPos = cam.transform.position;
            Vector3 camToTarget = _grabTarget - camPos;
            float camDist = camToTarget.magnitude;

            if (camDist > 0.001f &&
                Physics.Raycast(camPos, camToTarget.normalized, out RaycastHit camHit, camDist, blockMask))
            {
                float safeDist = Mathf.Max(0f, camHit.distance - margin);
                _grabTarget = camPos + camToTarget.normalized * safeDist;
            }
        }

        // 2) Current position → target: prevent tunneling through walls/barriers
        //    (always active — even when snapped to a surface)
        Vector3 from = _heldRb.position;
        Vector3 delta = _grabTarget - from;
        float dist = delta.magnitude;

        if (dist > 0.001f &&
            Physics.Raycast(from, delta.normalized, out RaycastHit wallHit, dist, blockMask))
        {
            float safeDist = Mathf.Max(0f, wallHit.distance - margin);
            _grabTarget = from + delta.normalized * safeDist;
        }
    }

    // ── Rotate input (RMB / gamepad RB) ─────────────────────────────

    private void UpdateScrollInput()
    {
        // RMB = rotate around Y (turn)
        bool rotatePressed = UnityEngine.InputSystem.Mouse.current != null
            && UnityEngine.InputSystem.Mouse.current.rightButton.wasPressedThisFrame;
        if (!rotatePressed
            && UnityEngine.InputSystem.Gamepad.current != null
            && UnityEngine.InputSystem.Gamepad.current.rightShoulder.wasPressedThisFrame)
            rotatePressed = true;

        if (rotatePressed)
        {
            float angle = scrollRotateStep;
            if (_isOnWall)
                _wallRotation += angle;
            else
                _held.transform.Rotate(0f, angle, 0f, Space.World);
        }

        // Shift+RMB or Mouse Back Button (3) = flip upright/flat
        bool flipPressed = Input.GetMouseButtonDown(3); // mouse back/thumb button
        if (!flipPressed)
        {
            flipPressed = (Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift))
                       && Input.GetMouseButtonDown(1);
        }

        if (flipPressed)
        {
            // Toggle between standing (upright) and lying flat
            Vector3 euler = _held.transform.eulerAngles;
            float xAngle = Mathf.DeltaAngle(euler.x, 0f);
            bool isUpright = Mathf.Abs(xAngle) < 45f;

            if (isUpright)
                _held.transform.Rotate(90f, 0f, 0f, Space.Self); // lay flat
            else
                _held.transform.rotation = Quaternion.Euler(0f, euler.y, 0f); // stand up
        }
    }

    // ── Helper: half-extent along a normal ────────────────────────────

    private const float PlacementSafetyMargin = 0.02f;

    private float GetHeldHalfExtentAlongNormal(Vector3 normal)
    {
        // Use cached extents (colliders are disabled while held)
        return Mathf.Abs(Vector3.Dot(_heldBoundsExtents, normal.normalized)) + PlacementSafetyMargin;
    }

    /// <summary>
    /// Lock a slot-deposited item (and any paired children) so it can't fall
    /// out of the slot or get bumped around. Reverted on next pickup via
    /// PlaceableObject.OnPickedUp, which sets isKinematic = false.
    /// </summary>
    private static void LockRigidbodyAtSlot(PlaceableObject po)
    {
        if (po == null) return;

        var rb = po.GetComponent<Rigidbody>();
        if (rb != null)
        {
            rb.linearVelocity = Vector3.zero;
            rb.angularVelocity = Vector3.zero;
            rb.isKinematic = true;
            rb.useGravity = false;
        }

        // Paired partner is parented under this transform — lock it too.
        var childRbs = po.GetComponentsInChildren<Rigidbody>();
        for (int i = 0; i < childRbs.Length; i++)
        {
            if (childRbs[i] == rb) continue;
            childRbs[i].linearVelocity = Vector3.zero;
            childRbs[i].angularVelocity = Vector3.zero;
            childRbs[i].isKinematic = true;
            childRbs[i].useGravity = false;
        }
    }

    // Buffer reused by FindOccupant — keeps the helper allocation-free.
    private static readonly Collider[] s_occupancyBuffer = new Collider[16];

    /// <summary>
    /// Returns a PlaceableObject occupying the cell at <paramref name="worldPos"/>
    /// for the held item, or null if the cell is free. Excludes the held item itself
    /// and any of its children. Used for placement gating and shadow color.
    /// </summary>
    private PlaceableObject FindOccupant(Vector3 worldPos)
    {
        if (_held == null) return null;

        // Use the larger horizontal half-extent shrunk slightly so flush neighbors
        // along the grid don't trip the check.
        float radius = Mathf.Max(_heldBoundsExtents.x, _heldBoundsExtents.z) * 0.85f;
        if (radius < 0.02f) radius = 0.02f;

        int count = Physics.OverlapSphereNonAlloc(worldPos, radius, s_occupancyBuffer, placeableLayer);
        for (int i = 0; i < count; i++)
        {
            var po = s_occupancyBuffer[i].GetComponentInParent<PlaceableObject>();
            if (po == null) continue;
            if (po == _held) continue;
            if (po.transform.IsChildOf(_held.transform)) continue;
            return po;
        }
        return null;
    }

    // ── Shadow preview ──────────────────────────────────────────────

    private void BuildShadow()
    {
        _shadowGO = new GameObject("PlacementShadow");
        _shadowGO.transform.SetParent(transform);

        var mf = _shadowGO.AddComponent<MeshFilter>();
        _shadowRenderer = _shadowGO.AddComponent<MeshRenderer>();

        var mesh = new Mesh { name = "ShadowQuad" };
        mesh.vertices = new[]
        {
            new Vector3(-0.5f, 0f, -0.5f),
            new Vector3( 0.5f, 0f, -0.5f),
            new Vector3( 0.5f, 0f,  0.5f),
            new Vector3(-0.5f, 0f,  0.5f)
        };
        mesh.uv = new[]
        {
            new Vector2(0f, 0f), new Vector2(1f, 0f),
            new Vector2(1f, 1f), new Vector2(0f, 1f)
        };
        mesh.triangles = new[] { 0, 2, 1, 0, 3, 2 };
        mesh.RecalculateNormals();
        mf.sharedMesh = mesh;

        int texSize = 32;
        var tex = new Texture2D(texSize, texSize, TextureFormat.RGBA32, false);
        tex.filterMode = FilterMode.Bilinear;
        tex.wrapMode = TextureWrapMode.Clamp;
        float center = texSize * 0.5f;
        float radius = center - 1f;
        for (int y = 0; y < texSize; y++)
        {
            for (int x = 0; x < texSize; x++)
            {
                float dist = Vector2.Distance(new Vector2(x, y), new Vector2(center, center));
                float a = Mathf.Clamp01((radius - dist) / 2f);
                tex.SetPixel(x, y, new Color(1f, 1f, 1f, a));
            }
        }
        tex.Apply();

        var shader = Shader.Find("Universal Render Pipeline/Particles/Unlit");
        if (shader == null) shader = Shader.Find("Sprites/Default");
        if (shader == null) shader = Shader.Find("Unlit/Transparent");
        _shadowMat = new Material(shader);
        _shadowMat.mainTexture = tex;
        _shadowMat.color = s_shadowValid;
        _shadowMat.SetFloat("_Surface", 1f);
        _shadowMat.SetFloat("_Blend", 0f);
        _shadowMat.SetInt("_ZTest", (int)CompareFunction.Always);
        _shadowMat.renderQueue = 3900;
        _shadowRenderer.sharedMaterial = _shadowMat;
        _shadowRenderer.shadowCastingMode = ShadowCastingMode.Off;
        _shadowRenderer.receiveShadows = false;

        _shadowGO.SetActive(false);
    }

    private void ShowShadow(bool show)
    {
        if (_shadowGO != null)
            _shadowGO.SetActive(show);
    }

    // ── Ghost preview ──────────────────────────────────────────────

    /// <summary>
    /// Build a translucent clone of the held item, reparented under a ghost
    /// root so we can move it to the grid-snapped position each frame. The
    /// player sees exactly where the real item will land without breaking the
    /// smooth carry motion of the held item itself.
    /// </summary>
    private void BuildGhostPreview(PlaceableObject source)
    {
        if (!_useGhostPreview || source == null) return;
        DestroyGhostPreview();

        _ghostPreviewGO = Instantiate(source.gameObject);
        _ghostPreviewGO.name = $"GhostPreview_{source.name}";
        _ghostPreviewGO.transform.localScale = source.transform.lossyScale;

        // Strip everything that isn't a pure visual (transform + mesh render).
        // Destroy RequireComponent owners first (PlaceableObject → Rigidbody/Collider
        // dependency) so their dependencies can be removed in the second pass.
        foreach (var po in _ghostPreviewGO.GetComponentsInChildren<PlaceableObject>(true))
            DestroyImmediate(po);
        foreach (var pi in _ghostPreviewGO.GetComponentsInChildren<PairableItem>(true))
            DestroyImmediate(pi);

        var comps = _ghostPreviewGO.GetComponentsInChildren<Component>(includeInactive: true);
        for (int i = 0; i < comps.Length; i++)
        {
            var c = comps[i];
            if (c == null) continue;
            if (c is Transform) continue;
            if (c is MeshFilter) continue;
            if (c is MeshRenderer) continue;
            Destroy(c);
        }

        // Force every layer to IgnoreRaycast so the ghost never catches
        // cursor raycasts, occupancy checks, or placement surface hits.
        int ignoreLayer = 2; // built-in IgnoreRaycast
        foreach (Transform t in _ghostPreviewGO.GetComponentsInChildren<Transform>(true))
            t.gameObject.layer = ignoreLayer;

        // Replace materials with a translucent tint version so the ghost looks
        // like a semi-see-through preview instead of a solid duplicate.
        _ghostPreviewMats.Clear();
        var ghostShader = Shader.Find("Universal Render Pipeline/Particles/Unlit");
        if (ghostShader == null) ghostShader = Shader.Find("Sprites/Default");
        var renderers = _ghostPreviewGO.GetComponentsInChildren<Renderer>(includeInactive: true);
        for (int i = 0; i < renderers.Length; i++)
        {
            var r = renderers[i];
            if (r == null) continue;
            var mat = new Material(ghostShader);
            mat.SetFloat("_Surface", 1f);
            mat.SetFloat("_Blend", 0f);
            mat.SetFloat("_ZWrite", 0f);
            mat.SetOverrideTag("RenderType", "Transparent");
            mat.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");
            mat.renderQueue = 3100;
            mat.color = _ghostTint;
            r.sharedMaterial = mat;
            r.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            r.receiveShadows = false;
            _ghostPreviewMats.Add(mat);
        }

        _ghostPreviewGO.SetActive(false); // hidden until UpdateShadow positions it
    }

    /// <summary>Position the ghost at the currently-planned placement pose.</summary>
    private void UpdateGhostPreview(Vector3 worldPos, Quaternion worldRot, bool show)
    {
        if (_ghostPreviewGO == null) return;
        if (show)
        {
            _ghostPreviewGO.transform.SetPositionAndRotation(worldPos, worldRot);
            if (!_ghostPreviewGO.activeSelf)
                _ghostPreviewGO.SetActive(true);
        }
        else if (_ghostPreviewGO.activeSelf)
        {
            _ghostPreviewGO.SetActive(false);
        }
    }

    private void DestroyGhostPreview()
    {
        for (int i = 0; i < _ghostPreviewMats.Count; i++)
            if (_ghostPreviewMats[i] != null) Destroy(_ghostPreviewMats[i]);
        _ghostPreviewMats.Clear();

        if (_ghostPreviewGO != null)
        {
            Destroy(_ghostPreviewGO);
            _ghostPreviewGO = null;
        }
    }

    private void UpdateShadow()
    {
        if (_shadowGO == null || _heldRb == null) return;

        // Only show shadow when hovering a valid placement surface
        if (_currentSurface == null)
        {
            _shadowGO.SetActive(false);
            UpdateGhostPreview(Vector3.zero, Quaternion.identity, show: false);
            return;
        }

        _shadowGO.SetActive(true);

        var hitResult = _currentSurface.ProjectOntoSurface(_grabTarget, cam.transform.position);

        // Slot-zone fast path: if the surface has a slotted DropZone the held
        // item belongs to, the shadow follows the slot — not the cursor — and
        // is green whenever the rack has any free slot. The actual click goes
        // through the auto-slot deposit, which doesn't care about grid cells.
        var slotZone = _currentSurface.GetComponent<DropZone>();
        if (slotZone == null) slotZone = _currentSurface.GetComponentInParent<DropZone>();
        bool isSlotZoneMatch = slotZone != null && slotZone.UseSlotting && _held != null
            && (slotZone.ZoneName == _held.HomeZoneName || slotZone.ZoneName == _held.AltHomeZoneName);

        if (isSlotZoneMatch)
        {
            bool slotFree = slotZone.TryPeekNextDepositSlot(out Vector3 slotPos, out Quaternion slotRot);
            Vector3 slotShadow = slotFree
                ? slotPos + hitResult.surfaceNormal * 0.01f
                : hitResult.worldPosition + hitResult.surfaceNormal * 0.01f;

            _shadowMat.color = slotFree ? s_shadowValid : s_shadowInvalid;
            _shadowGO.transform.position = slotShadow;
            _shadowGO.transform.rotation = Quaternion.FromToRotation(Vector3.up, hitResult.surfaceNormal);
            _shadowGO.transform.localScale = new Vector3(_heldShadowDiameter, 1f, _heldShadowDiameter);

            // Ghost preview follows the slot pose (not the cursor) when snapping.
            UpdateGhostPreview(slotFree ? slotPos : hitResult.worldPosition,
                               slotFree ? slotRot : Quaternion.identity,
                               show: slotFree);
            return;
        }

        // Snap the preview to the same grid cell Place() will use, so what you
        // see is exactly what you'll get.
        Vector3 snapped = _currentSurface.SnapToGrid(hitResult.worldPosition, gridSize, cam.transform.position);
        float halfExtent = GetHeldHalfExtentAlongNormal(hitResult.surfaceNormal);
        Vector3 placePos = snapped + hitResult.surfaceNormal * halfExtent;

        Quaternion placeRot = _currentSurface.IsVertical
            ? Quaternion.LookRotation(hitResult.surfaceNormal, Vector3.up)
              * Quaternion.AngleAxis(_wallRotation, Vector3.forward)
            : _held.transform.rotation;

        // Mirror the home-snap override from Place() so ghost matches exactly
        if (_held.HasHome && Vector3.Distance(placePos, _held.HomePosition) < _held.HomeTolerance * 2f)
        {
            placePos = _held.HomePosition;
            placeRot = _held.HomeRotation;
        }

        Vector3 shadowPos = snapped + hitResult.surfaceNormal * 0.01f;
        Quaternion shadowRot = Quaternion.FromToRotation(Vector3.up, hitResult.surfaceNormal);

        bool canPlace = (!_currentSurface.IsVertical || _held.CanWallMount)
            && (_currentSurface.IsVertical || !_held.WallOnly);

        // Trash items only show valid on floor surfaces and trash cans
        if (canPlace && _held.Category == ItemCategory.Trash)
        {
            var zone = _currentSurface.GetComponent<DropZone>();
            bool isTrashCan = zone != null && zone.DestroyOnDeposit;
            canPlace = _currentSurface.IsFloor || isTrashCan;
        }

        // Occupancy: blocked unless the occupant is a valid pair partner of the held item.
        if (canPlace)
        {
            var occupant = FindOccupant(placePos);
            if (occupant != null)
            {
                var heldPair = _held.GetComponent<PairableItem>();
                var occPair = occupant.GetComponent<PairableItem>();
                bool canStackHere = heldPair != null && occPair != null
                    && occPair.CanPairWith(heldPair);
                if (!canStackHere) canPlace = false;
            }
        }

        _shadowMat.color = canPlace ? s_shadowValid : s_shadowInvalid;
        _shadowGO.transform.position = shadowPos;
        _shadowGO.transform.rotation = shadowRot;
        _shadowGO.transform.localScale = new Vector3(_heldShadowDiameter, 1f, _heldShadowDiameter);

        // Ghost preview sits at the planned landing pose so the player sees
        // a translucent copy of the item "parked" at the snapped grid cell.
        UpdateGhostPreview(placePos, placeRot, show: canPlace);
    }

    // ── Public API ──────────────────────────────────────────────────

    /// <summary>
    /// Enable or disable grabbing. Called by ApartmentManager during state transitions.
    /// When disabled while holding, forces a drop onto the nearest surface.
    /// </summary>
    public void SetEnabled(bool enabled)
    {
        _isEnabled = enabled;

        if (!enabled && _held != null)
        {
            // Restore rotation constraints before configuring rigidbody
            _heldRb.constraints = _originalConstraints;

            var nearest = FindNearestSurfaceForHeld(_heldRb.position);
            if (nearest != null)
            {
                var hitResult = nearest.ProjectOntoSurface(_heldRb.position, cam != null ? cam.transform.position : (Vector3?)null);
                float halfExtent = GetHeldHalfExtentAlongNormal(hitResult.surfaceNormal);
                Vector3 pos = hitResult.worldPosition + hitResult.surfaceNormal * halfExtent;
                Quaternion rot = nearest.IsVertical
                    ? Quaternion.LookRotation(hitResult.surfaceNormal, Vector3.up)
                    : _held.transform.rotation;

                _heldRb.linearVelocity = Vector3.zero;
                _held.OnPlaced(nearest, false, pos, rot);

                // Book public/private toggle on force-drop
                var bookItem = _held.GetComponent<BookItem>();
                if (bookItem != null) bookItem.OnBookPlaced(nearest);

                // Stack-aware plate hooks on force-drop. Auto-stack-on-place
                // is gone — pairing is the only stack path now.
                var stackable = _held.GetComponent<StackablePlate>();
                if (stackable != null)
                {
                    var dropZone = nearest.GetComponent<DishDropZone>();
                    if (dropZone != null)
                    {
                        dropZone.RegisterDeposit(stackable);
                        var childPlates = stackable.GetComponentsInChildren<StackablePlate>();
                        foreach (var child in childPlates)
                        {
                            if (child != stackable)
                                dropZone.RegisterDeposit(child);
                        }
                    }
                }
            }
            else
            {
                _heldRb.useGravity = true;
                _heldRb.linearVelocity = Vector3.zero;
                _held.OnDropped();
            }

            ClearHeld();
        }
    }

    private PlacementSurface FindNearestSurfaceForHeld(Vector3 worldPos)
    {
        if (_held == null) return PlacementSurface.FindNearest(worldPos);
        return PlacementSurface.FindNearest(worldPos,
            skipVertical: !_held.CanWallMount,
            skipHorizontal: _held.WallOnly);
    }
}
