using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.Rendering;

public class ObjectGrabber : MonoBehaviour
{
    [Header("Physics")]
#pragma warning disable 0414
    [Tooltip("Spring strength pulling the object toward the cursor.")]
    [SerializeField] private float grabSpring = 120f;

    [Tooltip("Damper opposing overshoot.")]
    [SerializeField] private float grabDamper = 18f;

    [Tooltip("Maximum acceleration applied to the grabbed object.")]
    [SerializeField] private float maxAccel = 60f;

    [Tooltip("Maximum speed cap to prevent tunneling.")]
    [SerializeField] private float maxSpeed = 12f;
#pragma warning restore 0414

    // ── Grab feel presets (switchable at runtime via F3 debug panel) ──
    public enum GrabFeel
    {
        Default,   // current — snappy, direct
        Plucky,    // resistant tug, bouncy release — leaf-pulling feel
        Floaty,    // slow, dreamy, drifty — underwater feel
        Snappy,    // instant, no lag — arcade feel
        Heavy,     // sluggish, weighty — moving furniture feel
    }

    private static GrabFeel s_currentFeel = GrabFeel.Default;
    public static GrabFeel CurrentFeel
    {
        get => s_currentFeel;
        set
        {
            s_currentFeel = value;
            Debug.Log($"[ObjectGrabber] Grab feel: {value}");
        }
    }

    public static void CycleGrabFeel()
    {
        var values = System.Enum.GetValues(typeof(GrabFeel));
        int next = ((int)s_currentFeel + 1) % values.Length;
        CurrentFeel = (GrabFeel)next;
    }

    // Preset tuning values: spring, damper, maxAccel, maxSpeed
    private static readonly (float spring, float damper, float accel, float speed)[] s_feelPresets =
    {
        (120f, 18f, 60f,  12f),  // Default — snappy, direct
        (35f,  6f,  20f,  5f),   // Plucky — low spring, low damper = stretchy tug + overshoot bounce
        (25f,  12f, 15f,  4f),   // Floaty — low spring, high damper = slow drift, no bounce
        (500f, 40f, 200f, 25f),  // Snappy — very stiff, instant follow
        (50f,  25f, 25f,  3f),   // Heavy — medium spring, high damper, low speed cap
    };

    // Runtime overrides (driven by debug sliders, -1 = use preset)
    private static float s_overrideSpring = -1f;
    private static float s_overrideDamper = -1f;
    private static float s_overrideAccel = -1f;
    private static float s_overrideSpeed = -1f;

    public static void SetGrabOverrides(float spring, float damper, float accel, float speed)
    {
        s_overrideSpring = spring;
        s_overrideDamper = damper;
        s_overrideAccel = accel;
        s_overrideSpeed = speed;
    }

    public static void GetCurrentGrabParams(out float spring, out float damper, out float accel, out float speed)
    {
        if (s_overrideSpring > 0f)
        {
            spring = s_overrideSpring; damper = s_overrideDamper;
            accel = s_overrideAccel; speed = s_overrideSpeed;
            return;
        }
        var p = s_feelPresets[(int)s_currentFeel];
        spring = p.spring; damper = p.damper; accel = p.accel; speed = p.speed;
    }

    private void GetActiveGrabParams(out float spring, out float damper, out float accel, out float speed)
    {
        if (s_overrideSpring > 0f)
        {
            spring = s_overrideSpring;
            damper = s_overrideDamper;
            accel = s_overrideAccel;
            speed = s_overrideSpeed;
            return;
        }
        var p = s_feelPresets[(int)s_currentFeel];
        spring = p.spring;
        damper = p.damper;
        accel = p.accel;
        speed = p.speed;
    }

    [Header("Grid Snap")]
    [Tooltip("Grid cell size in world units. Placement is always grid-snapped — no toggle.")]
    [SerializeField] private float gridSize = 0.03f;

    [Tooltip("Multiplier for wall grid size. Walls feel better with a coarser grid (2-3x). 1 = same as tables.")]
    [SerializeField] private float _wallGridMultiplier = 2f;

    /// <summary>Grid size adjusted for wall surfaces.</summary>
    private float GetGridSize(PlacementSurface surface)
    {
        return surface != null && surface.IsVertical ? gridSize * _wallGridMultiplier : gridSize;
    }

    public float GridSize
    {
        get => gridSize;
        set => gridSize = Mathf.Max(0.01f, value);
    }

    /// <summary>Global grid cell size, set in Awake. PlaceableObject reads this on Start to snap scene-placed items.</summary>
    public static float GlobalGridSize { get; private set; } = 0.03f;

    [Header("Scroll Behavior")]
    [Tooltip("Degrees rotated per scroll tick around Y axis.")]
    [SerializeField] private float scrollRotateStep = 45f;

    [Header("Raycast")]
    [Tooltip("Layer mask for placeable objects.")]
    [SerializeField] private LayerMask placeableLayer = ~0;

    [Tooltip("Layer mask for surface triggers (auto-generated by PlacementSurface).")]
    [SerializeField] private LayerMask surfaceLayer;

    [Tooltip("Camera used for raycasting. Auto-finds MainCamera if null.")]
    [SerializeField] private Camera cam;

    [Tooltip("Layer mask for wall/ceiling/floor geometry that held items cannot pass through.")]
    [SerializeField] private LayerMask _wallLayer = 1; // Default layer

    [Tooltip("Additional layer mask for barriers (closed cubbies, custom blockers). Merged with _wallLayer for clamping.")]
    [SerializeField] private LayerMask _barrierLayer;

    [Header("Audio")]
    [Tooltip("SFX played when picking up an object.")]
    [SerializeField] private AudioClip _pickupSFX;

    [Tooltip("SFX played when placing an object on a surface.")]
    [SerializeField] private AudioClip _placeSFX;

    [Header("Tether")]
    [Tooltip("Max distance between grab target and held object before teleporting to catch up.")]
    [SerializeField] private float maxTetherDistance = 3f;

    // Input managed by IrisInput singleton

    private bool _isEnabled;

    /// <summary>Fired after an object is placed on a surface. Arg: the placed object.</summary>
    public static event System.Action<PlaceableObject> OnObjectPlaced;

    private static ObjectGrabber s_instance;

    /// <summary>True when any ObjectGrabber is holding an object. Check this to block other interactions.</summary>
    public static bool IsHoldingObject => s_instance != null && s_instance._held != null;

    /// <summary>The currently held PlaceableObject, or null if nothing is held.</summary>
    public static PlaceableObject HeldObject => s_instance != null ? s_instance._held : null;

    /// <summary>The surface the held object is currently hovering over, or null.</summary>
    public static PlacementSurface CurrentSurface => s_instance != null ? s_instance._currentSurface : null;

    /// <summary>
    /// True when ObjectGrabber consumed a click this frame (picked up, placed, toggled drawer/switch).
    /// Other click-driven systems should check this to avoid processing the same click.
    /// </summary>
    public static bool ClickConsumedThisFrame { get; private set; }
    private static int s_lastConsumedFrame = -1;

    /// <summary>Force-release the held item without placing. Used by FridgeController deposit.</summary>
    public static void ForceReleaseHeld()
    {
        if (s_instance != null && s_instance._held != null)
            s_instance.ClearHeld();
    }

    private PlaceableObject _held;
    private Rigidbody _heldRb;
    private Vector3 _grabTarget;
    private float _fallbackDepth;
    private RigidbodyConstraints _originalConstraints;
    private float _heldShadowDiameter;
    private Vector3 _heldBoundsExtents;

    // Pickup feel: plucky spring on pickup, then ramp to stiff carry
    private float _pickupTimer;
    private const float PickupFeelDuration = 0.25f; // seconds of plucky feel after pickup

    // Surface tracking
    private PlacementSurface _currentSurface;
    private PlacementSurface _lastValidSurface;
    private float _wallRotation;
    private bool _isOnWall;

    // Double-click detection for plate unstacking
    private float _lastClickTime;
    private const float DoubleClickThreshold = 0.3f;

    // Shadow preview
    private GameObject _shadowGO;
    private MeshRenderer _shadowRenderer;
    private Material _shadowMat;
    private static readonly Color s_shadowValid = new Color(0.25f, 0.9f, 0.3f, 0.75f);
    private static readonly Color s_shadowInvalid = new Color(0.95f, 0.18f, 0.2f, 0.75f);

    // Ghost preview (translucent copy of the held item at the snapped grid cell)
    [Header("Ghost Preview")]
    [Tooltip("If true, a translucent duplicate of the held item is shown at the grid-snapped cell so the player sees exactly where it will land. Works alongside the disc shadow.")]
    [SerializeField] private bool _useGhostPreview = true;
    [Tooltip("Tint applied to the ghost preview when placement is valid.")]
    [SerializeField] private Color _ghostTint = new Color(0.5f, 0.95f, 0.55f, 0.35f);
    [Tooltip("Tint applied to the ghost preview when the item can't fit / can't be placed.")]
    [SerializeField] private Color _ghostTintInvalid = new Color(0.95f, 0.2f, 0.2f, 0.35f);
    private GameObject _ghostPreviewGO;
    private readonly List<Material> _ghostPreviewMats = new();

    private void Awake()
    {
        s_instance = this;
        GlobalGridSize = gridSize;

        if (cam == null)
            cam = Camera.main;

        // Load default click SFX from Resources if none assigned in Inspector
        if (_pickupSFX == null)
            _pickupSFX = Resources.Load<AudioClip>("Audio/default_click");
        if (_placeSFX == null)
            _placeSFX = Resources.Load<AudioClip>("Audio/default_click");

        BuildShadow();
    }

    // Input managed by IrisInput singleton — no local enable/disable needed.

    private void OnDestroy()
    {
        if (s_instance == this) s_instance = null;
        if (_shadowMat != null) Destroy(_shadowMat);
        DestroyGhostPreview();
    }

    private void Update()
    {
        if (DayPhaseManager.Instance != null && !DayPhaseManager.Instance.IsInteractionPhase)
            return;

        if (!_isEnabled) return;

        // Reset click consumption flag at start of each frame
        if (Time.frameCount != s_lastConsumedFrame)
            ClickConsumedThisFrame = false;

        if (IrisInput.Instance != null && IrisInput.Instance.Click.WasPressedThisFrame())
        {
            // Block game-world clicks when pointer is over UI
            if (EventSystem.current != null && EventSystem.current.IsPointerOverGameObject())
                return;

            if (_held == null)
            {
                TryPickUp();
            }
            else
            {
                // Double-click while holding a plate stack → unstack top plate
                float now = Time.unscaledTime;
                bool isDoubleClick = (now - _lastClickTime) < DoubleClickThreshold;
                _lastClickTime = now;

                if (isDoubleClick && TryUnstackHeldPlate())
                {
                    ConsumeClick();
                    return;
                }

                // If holding a pairable item, check if clicking its match → snap pair.
                // This is the ONLY path for placing one item on top of another —
                // non-pairable items can't be stacked.
                if (TryPairWithClicked())
                {
                    ConsumeClick();
                    return;
                }

                Place();
                ConsumeClick();
            }
        }

        if (_held != null)
        {
            UpdateGrabTarget();
            ClampGrabTargetToWalls();
            UpdateScrollInput();
            UpdateShadow();
        }
        else
        {
            UpdateAlbumHover();
        }
    }

    // ── Album sleeve hover detection ────────────────────────────────

    private AlbumSleeve _lastHoveredSleeve;

    private void UpdateAlbumHover()
    {
        AlbumSleeve hovered = null;

        Ray ray = cam.ScreenPointToRay(IrisInput.CursorPosition);
        // Check both placeable layer and RecordSleeves layer (30) so all
        // sleeves are hoverable regardless of which layer they're on.
        int sleeveMask = placeableLayer | (1 << 30);
        if (Physics.Raycast(ray, out RaycastHit hit, 100f, sleeveMask))
        {
            hovered = hit.collider.GetComponent<AlbumSleeve>();
            if (hovered == null) hovered = hit.collider.GetComponentInParent<AlbumSleeve>();
        }

        if (hovered != _lastHoveredSleeve)
        {
            if (_lastHoveredSleeve != null)
                _lastHoveredSleeve.SetHovered(false);

            if (hovered != null)
            {
                hovered.SetHovered(true);
                PickupDescriptionHUD.Instance?.Show(hovered.GetTooltipText());
            }

            _lastHoveredSleeve = hovered;
        }
    }

    private void FixedUpdate()
    {
        if (_held == null || _heldRb == null) return;

        // Tether snap-back
        if (Vector3.Distance(_heldRb.position, _grabTarget) > maxTetherDistance)
        {
            _heldRb.position = _grabTarget;
            _heldRb.linearVelocity = Vector3.zero;
        }

        // Pickup feel: plucky spring for the first fraction of a second,
        // then ramp to stiff carry so the object follows smoothly.
        _pickupTimer = Mathf.Max(_pickupTimer - Time.fixedDeltaTime, 0f);
        float pickupT = Mathf.Clamp01(_pickupTimer / PickupFeelDuration); // 1 = just picked up, 0 = carrying

        GetActiveGrabParams(out float presetSpring, out float presetDamper,
            out float presetAccel, out float presetSpeed);

        // Carry params: stiff, direct follow
        const float carrySpring = 400f;
        const float carryDamper = 35f;
        const float carryAccel = 150f;
        const float carrySpeed = 20f;

        // Blend from preset (plucky) to carry (stiff)
        float activeSpring = Mathf.Lerp(carrySpring, presetSpring, pickupT);
        float activeDamper = Mathf.Lerp(carryDamper, presetDamper, pickupT);
        float activeMaxAccel = Mathf.Lerp(carryAccel, presetAccel, pickupT);
        float activeMaxSpeed = Mathf.Lerp(carrySpeed, presetSpeed, pickupT);

        Vector3 toTarget = _grabTarget - _heldRb.worldCenterOfMass;
        Vector3 force = toTarget * activeSpring - _heldRb.linearVelocity * activeDamper;

        if (force.sqrMagnitude > activeMaxAccel * activeMaxAccel)
            force = force.normalized * activeMaxAccel;

        _heldRb.AddForce(force, ForceMode.Acceleration);

        // Speed cap
        if (_heldRb.linearVelocity.sqrMagnitude > activeMaxSpeed * activeMaxSpeed)
            _heldRb.linearVelocity = _heldRb.linearVelocity.normalized * activeMaxSpeed;
    }

    // ── Pick up ──────────────────────────────────────────────────────

    private static void ConsumeClick()
    {
        ClickConsumedThisFrame = true;
        s_lastConsumedFrame = Time.frameCount;
    }

    /// <summary>Allow other systems (WateringManager, CleaningManager) to consume the click.</summary>
    public static void ConsumeClickExternal() => ConsumeClick();

    private void TryPickUp()
    {
        Vector2 screenPos = IrisInput.CursorPosition;
        Ray ray = cam.ScreenPointToRay(screenPos);

        // QueryTriggerInteraction.Collide so mess items (petals, trimmings)
        // with trigger colliders can be clicked. Also check RecordSleeves layer (30).
        int pickupMask = placeableLayer | (1 << 30);
        if (!Physics.Raycast(ray, out RaycastHit hit, 100f, pickupMask, QueryTriggerInteraction.Collide))
            return;

        var placeable = hit.collider.GetComponent<PlaceableObject>();
        if (placeable == null)
            placeable = hit.collider.GetComponentInParent<PlaceableObject>();

        // No placeable hit — check for cubby/drawer door click
        if (placeable == null)
        {
            var clickedDrawer = hit.collider.GetComponent<DrawerController>();
            if (clickedDrawer == null)
                clickedDrawer = hit.collider.GetComponentInParent<DrawerController>();

            if (clickedDrawer != null)
            {
                if (clickedDrawer.CurrentState == DrawerController.State.Closed)
                    clickedDrawer.Open();
                else if (clickedDrawer.CurrentState == DrawerController.State.Open)
                    clickedDrawer.Close();
                ConsumeClick();
                return;
            }

            // Check for Nema click — open personality/wellbeing panel (non-date only)
            var nema = hit.collider.GetComponent<NemaController>();
            if (nema == null) nema = hit.collider.GetComponentInParent<NemaController>();
            if (nema != null)
            {
                if (DayPhaseManager.Instance == null
                    || DayPhaseManager.Instance.CurrentPhase != DayPhaseManager.DayPhase.DateInProgress)
                {
                    NemaProfilePanel.Instance?.Open();
                    ConsumeClick();
                    return;
                }
            }

            // Check for light switch click
            var lightSwitch = hit.collider.GetComponent<LightSwitch>();
            if (lightSwitch == null)
                lightSwitch = hit.collider.GetComponentInParent<LightSwitch>();
            if (lightSwitch != null)
            {
                lightSwitch.Toggle();
                ConsumeClick();
                return;
            }

            // Check for turntable button click (play/pause)
            var turntableBtn = hit.collider.GetComponent<TurntableButton>();
            if (turntableBtn == null)
                turntableBtn = hit.collider.GetComponentInParent<TurntableButton>();
            if (turntableBtn != null)
            {
                turntableBtn.Press();
                ConsumeClick();
                return;
            }

            // Click on album sleeve — extract vinyl if hovered/peeking
            var clickedSleeve = hit.collider.GetComponent<AlbumSleeve>();
            if (clickedSleeve == null)
                clickedSleeve = hit.collider.GetComponentInParent<AlbumSleeve>();
            if (clickedSleeve != null && clickedSleeve.IsHovered)
            {
                var vinylPlaceable = clickedSleeve.ExtractVinyl();
                if (vinylPlaceable != null)
                {
                    ConsumeClick();
                    _held = vinylPlaceable;
                    _pickupTimer = PickupFeelDuration;
                    InitGrab();
                    return;
                }
            }

            // Click on a drink glass while not holding anything → finish the drink
            var clickedGlass = hit.collider.GetComponent<DrinkGlass>();
            if (clickedGlass == null)
                clickedGlass = hit.collider.GetComponentInParent<DrinkGlass>();
            if (clickedGlass != null && DrinkPourManager.Instance != null
                && DrinkPourManager.Instance.CurrentState == DrinkPourManager.State.Pouring
                && DrinkPourManager.Instance.ActiveGlass == clickedGlass)
            {
                DrinkPourManager.Instance.FinishDrink();
                ConsumeClick();
                return;
            }

            // Click on turntable while vinyl is loaded — eject to hand
            var clickedSlot = hit.collider.GetComponent<RecordSlot>();
            if (clickedSlot == null)
                clickedSlot = hit.collider.GetComponentInParent<RecordSlot>();
            if (clickedSlot != null && clickedSlot.IsLoaded)
            {
                var ejected = clickedSlot.EjectVinyl();
                if (ejected != null)
                {
                    ConsumeClick();
                    _held = ejected;
                    _pickupTimer = PickupFeelDuration;
                    InitGrab();
                    return;
                }
            }

            return;
        }

        if (placeable.CurrentState == PlaceableObject.State.Held)
            return;

        // Album sleeves are static — never grab them
        if (placeable.GetComponent<AlbumSleeve>() != null
            || placeable.GetComponentInParent<AlbumSleeve>() != null)
        {
            // But if the click hit the peeking vinyl, extract it
            var vinylOnSleeve = placeable.GetComponent<VinylDisc>();
            if (vinylOnSleeve == null) vinylOnSleeve = placeable.GetComponentInChildren<VinylDisc>();
            var parentSleeve = vinylOnSleeve != null ? vinylOnSleeve.HomeSleeve : null;
            if (parentSleeve != null && parentSleeve.IsHovered)
            {
                var vinylPlaceable = parentSleeve.ExtractVinyl();
                if (vinylPlaceable != null)
                {
                    ConsumeClick();
                    _held = vinylPlaceable;
                    _pickupTimer = PickupFeelDuration;
                    InitGrab();
                }
            }
            return; // never grab the sleeve itself
        }

        // Vinyl in album sleeve — extract on click (when sleeve is hovered / peeking)
        var vinylDisc = placeable.GetComponent<VinylDisc>();
        if (vinylDisc != null)
        {
            var sleeve = vinylDisc.HomeSleeve;
            if (sleeve != null && sleeve.IsHovered)
            {
                var vinylPlaceable = sleeve.ExtractVinyl();
                if (vinylPlaceable != null)
                {
                    ConsumeClick();
                    _held = vinylPlaceable;
                    _pickupTimer = PickupFeelDuration;
                    InitGrab();
                    return;
                }
            }
        }

        // Book collection: clicking a child book in a connected set detaches
        // just that book (for reordering) instead of picking up the whole group.
        var bookColl = placeable.GetComponent<BookCollectionItem>();
        if (bookColl != null && placeable.GetComponentInParent<PairableItem>() != null)
        {
            // Check if this is a CHILD in a paired stack (not the root)
            var parentPairable = placeable.transform.parent != null
                ? placeable.transform.parent.GetComponent<PairableItem>()
                : null;
            if (parentPairable != null)
            {
                var detached = bookColl.DetachFromStack();
                if (detached != null)
                {
                    ConsumeClick();
                    _held = detached;
                    _pickupTimer = PickupFeelDuration;
                    InitGrab();
                    return;
                }
            }
        }

        ConsumeClick();
        _held = placeable;
        _pickupTimer = PickupFeelDuration;
        InitGrab();
    }

    /// <summary>
    /// Shared grab initialization. Assumes _held and _pickupTimer are already set.
    /// Sets up physics, bounds cache, shadow, ghost preview, and description HUD.
    /// </summary>
    private void InitGrab()
    {
        var placeable = _held;

        // Flash partner highlight for pairable items (shoes)
        var pairable = placeable.GetComponent<PairableItem>();
        if (pairable != null) pairable.OnPickedUp();

        // Cache collider bounds BEFORE disabling — used for shadow size + surface offset
        var pickupCol = placeable.GetComponent<Collider>();
        if (pickupCol != null)
        {
            _heldBoundsExtents = pickupCol.bounds.extents;
            _heldShadowDiameter = Mathf.Max(_heldBoundsExtents.x, _heldBoundsExtents.z) * 2f * 1.3f;
        }
        else
        {
            _heldBoundsExtents = Vector3.one * 0.1f;
            _heldShadowDiameter = 0.3f;
        }

        // Detach from plate stack before pickup
        var stackable = placeable.GetComponent<StackablePlate>();
        if (stackable != null)
            stackable.PrepareForGrab();

        _heldRb = placeable.GetComponent<Rigidbody>();
        _heldRb.useGravity = false;
        _heldRb.isKinematic = false;
        _heldRb.collisionDetectionMode = CollisionDetectionMode.ContinuousDynamic;
        _grabTarget = _heldRb.worldCenterOfMass;

        // Store depth for floating fallback when cursor isn't over a surface
        _fallbackDepth = Vector3.Dot(
            _heldRb.worldCenterOfMass - cam.transform.position,
            cam.transform.forward);

        // Lock rotation so collisions don't spin the object
        _originalConstraints = _heldRb.constraints;
        _heldRb.constraints = _originalConstraints | RigidbodyConstraints.FreezeRotation;

        _currentSurface = placeable.LastPlacedSurface;
        _lastValidSurface = _currentSurface;
        _wallRotation = 0f;
        _isOnWall = false;

        placeable.OnPickedUp();

        // When picking up the watering can, blink all plants 3 times so
        // the player knows where to water.
        if (placeable.GetComponent<WateringCan>() != null)
            _plantBlinkRoutine = StartCoroutine(BlinkPlantHighlights(3));

        // When picking up a vinyl record, blink the turntable 3 times
        if (placeable.GetComponent<VinylDisc>() != null && RecordSlot.Instance != null)
            StartCoroutine(BlinkHighlight(RecordSlot.Instance.gameObject, 3));

        // Keep interactable highlight while held
        var heldHL = placeable.GetComponent<InteractableHighlight>();
        if (heldHL != null)
        {
            heldHL.SetHighlighted(true);
            heldHL.SetInteractHighlighted(true);
        }

        // Book hidden item check
        var bookItem = placeable.GetComponent<BookItem>();
        if (bookItem != null) bookItem.OnBookPickedUp();

        // Blanket fold + hidden item reveal
        var blanket = placeable.GetComponent<BlanketItem>();
        if (blanket != null) blanket.OnBlanketPickedUp();

        AudioManager.Instance?.PlaySFX(placeable.PickupSFXOverride != null ? placeable.PickupSFXOverride : _pickupSFX);
        ShowShadow(true);
        BuildGhostPreview(placeable);

        // Show pickup description
        if (PickupDescriptionHUD.Instance != null)
            PickupDescriptionHUD.Instance.Show(placeable.ItemDescription);
    }

    // ── Place ────────────────────────────────────────────────────────

    private void Place()
    {
        if (_held == null) return;

        // ── Watering can near plant ──
        if (_held.GetComponent<WateringCan>() != null)
        {
            var wm = WateringManager.Instance;

            if (_nearestWaterablePlant != null && wm != null)
            {
                // Not yet pouring this plant → start session
                if (wm.CurrentState != WateringManager.State.Pouring
                    || wm.ActivePlant != _nearestWaterablePlant)
                {
                    wm.StartWatering(_nearestWaterablePlant);
                    ConsumeClick();
                    return;
                }

                // Already pouring this plant → click does nothing (hold to pour)
                ConsumeClick();
                return;
            }

            // Not near any plant → end watering and place the can down
            if (wm != null && wm.CurrentState == WateringManager.State.Pouring)
                wm.EndWatering();
        }

        // ── Bottle near glass → start pouring instead of placing ──
        // Only during BackgroundJudging date phase — bottles are normal items otherwise.
        bool isDrinkPhase = DateSessionManager.Instance != null
            && DateSessionManager.Instance.CurrentDatePhase == DateSessionManager.DatePhase.BackgroundJudging;
        var heldBottle = _held.GetComponent<BottleItem>();
        if (isDrinkPhase && heldBottle != null && heldBottle.Ingredient != null && _nearestDrinkGlass != null)
        {
            if (DrinkPourManager.Instance != null)
            {
                // If this ingredient was already poured into this glass during
                // the current session, the player wants to put the bottle down
                // rather than re-enter the pour loop.
                bool alreadyPoured =
                    DrinkPourManager.Instance.CurrentState == DrinkPourManager.State.Pouring
                    && DrinkPourManager.Instance.ActiveGlass == _nearestDrinkGlass
                    && _nearestDrinkGlass.PourOrder.Contains(heldBottle.Ingredient);

                if (alreadyPoured)
                {
                    DrinkPourManager.Instance.StopPouring();
                    // Fall through to normal placement
                }
                else
                {
                    DrinkPourManager.Instance.StartPouring(_nearestDrinkGlass, heldBottle.Ingredient);
                    ConsumeClick();
                    return; // keep holding the bottle
                }
            }
        }

        // ── Deliver finished drink to date character ──
        if (_held.GetComponent<DrinkGlass>() != null
            && DrinkPourManager.Instance != null
            && DrinkPourManager.Instance.CurrentState == DrinkPourManager.State.WaitingForDelivery
            && DateSessionManager.Instance != null
            && DateSessionManager.Instance.DateCharacter != null)
        {
            // Proximity check — click anywhere while near the date to deliver.
            // More forgiving than requiring a precise raycast hit on the character model.
            Vector3 datePos = DateSessionManager.Instance.DateCharacter.transform.position;
            float dist = Vector3.Distance(_grabTarget, datePos);
            if (dist < 1.5f)
            {
                DrinkPourManager.Instance.DeliverToDate();
                ClearHeld();
                ConsumeClick();
                return;
            }

            // Fallback: raycast through all objects to find the date character
            Ray deliverRay = cam.ScreenPointToRay(IrisInput.CursorPosition);
            var hits = Physics.RaycastAll(deliverRay, 100f);
            for (int i = 0; i < hits.Length; i++)
            {
                var dateChar = hits[i].collider.GetComponent<DateCharacterController>();
                if (dateChar == null) dateChar = hits[i].collider.GetComponentInParent<DateCharacterController>();
                if (dateChar != null)
                {
                    DrinkPourManager.Instance.DeliverToDate();
                    ClearHeld();
                    ConsumeClick();
                    return;
                }
            }
        }

        // ── DiscoBall check ──
        if (_currentSurface != null)
        {
            var disco = _currentSurface.GetComponentInParent<DiscoBallController>();
            if (disco != null && _held.GetComponent<DiscoBallBulb>() != null)
            {
                _heldRb.constraints = _originalConstraints;
                _heldRb.linearVelocity = Vector3.zero;
                if (disco.TryAcceptBulb(_held))
                {
                    PlayPlaceSFX(_held);
                    ClearHeld();
                    return;
                }
            }
        }

        // ── Vinyl placement ──
        var heldVinyl = _held.GetComponent<VinylDisc>();
        if (heldVinyl != null)
        {
            // Try placing on turntable
            if (RecordSlot.Instance != null && RecordSlot.Instance.TryAcceptVinyl(_held))
            {
                PlayPlaceSFX(_held);
                ClearHeld();
                ConsumeClick();
                return;
            }

            // Try returning to home sleeve
            if (heldVinyl.HomeSleeve != null && heldVinyl.HomeSleeve.WaitingForReturn)
            {
                Ray returnRay = cam.ScreenPointToRay(IrisInput.CursorPosition);
                if (Physics.Raycast(returnRay, out RaycastHit sleeveHit, 100f))
                {
                    var sleeve = sleeveHit.collider.GetComponent<AlbumSleeve>();
                    if (sleeve == null) sleeve = sleeveHit.collider.GetComponentInParent<AlbumSleeve>();
                    if (sleeve != null && sleeve == heldVinyl.HomeSleeve)
                    {
                        sleeve.ReturnVinyl(heldVinyl);
                        ClearHeld();
                        ConsumeClick();
                        return;
                    }
                }
            }
        }

        // Check if clicking directly on a DropZone (trash can body, fridge, etc.)
        // This runs regardless of surface state so clicking anywhere on the
        // trash can (body or lid) deposits trash.
        if (TryDepositAtNearbyZone())
        {
            ConsumeClick();
            return;
        }

        // Proximity deposit: if the item was magnetically pulled close to a
        // destroy zone (trash can, sink), deposit it even if the click missed
        // the zone's collider (hit the counter behind it instead).
        if (_held.Category == ItemCategory.Trash || _held.Category == ItemCategory.Dish)
        {
            var allZones = DropZone.All;
            for (int i = 0; i < allZones.Count; i++)
            {
                var z = allZones[i];
                if (z == null || !z.DestroyOnDeposit) continue;

                bool matches = (_held.Category == ItemCategory.Trash && z.ZoneName == "TrashCan")
                            || (_held.Category == ItemCategory.Dish && z.ZoneName == "Sink")
                            || z.ZoneName == _held.HomeZoneName
                            || z.ZoneName == _held.AltHomeZoneName;
                if (!matches) continue;

                float dist = Vector3.Distance(z.transform.position, _grabTarget);
                if (dist < _trashSnapRadius)
                {
                    z.RegisterDeposit(_held);
                    ClearHeld();
                    ConsumeClick();
                    return;
                }
            }
        }

        // No surface under cursor — snap to the nearest surface as a fallback
        // so items don't free-fall through the floor. BUT only if there's no
        // barrier geometry nearby — if the occlusion check rejected surfaces
        // because of a barrier (inside furniture), don't bypass it with fallback.
        if (_currentSurface == null)
        {
            int blockMask = _wallLayer | _barrierLayer;
            bool nearBarrier = Physics.CheckSphere(_grabTarget, 0.15f, blockMask);
            if (nearBarrier) return; // inside furniture — don't place here

            var fallbackSurface = PlacementSurface.FindNearest(_grabTarget, skipVertical: true);
            if (fallbackSurface == null) return;
            _currentSurface = fallbackSurface;
        }

        // ── DropZone check ──
        // Only match the DropZone directly on this surface — parent/child
        // traversal was causing the kitchen counter to match the nearby sink.
        {
            DropZone zone = _currentSurface.GetComponent<DropZone>();
            bool zoneIsDirect = zone != null; // true = zone is on this surface, not found via proximity

            // Proximity fallback for non-destroy zones only (shoe rack, etc.).
            // Destroy zones (sink, trash can) must be placed directly on a
            // surface to match — otherwise adjacent surfaces steal deposits.
            if (zone == null)
            {
                float bestDist = float.MaxValue;
                var allZones = DropZone.All;
                for (int i = 0; i < allZones.Count; i++)
                {
                    var z = allZones[i];
                    if (z == null) continue;
                    if (z.DestroyOnDeposit) continue; // skip sink/trash — direct match only

                    float dist = Vector3.Distance(z.transform.position, _grabTarget);
                    if (dist < 2f && dist < bestDist)
                    {
                        bestDist = dist;
                        zone = z;
                    }
                }
            }

            if (zone != null)
            {
                bool matchesHome = (!string.IsNullOrEmpty(_held.HomeZoneName) && zone.ZoneName == _held.HomeZoneName)
                    || (!string.IsNullOrEmpty(_held.AltHomeZoneName) && zone.ZoneName == _held.AltHomeZoneName);
                // Category-specific destroy zones (trash→TrashCan, dishes→Sink, milk→Fridge)
                if (!matchesHome && zone.DestroyOnDeposit)
                {
                    if (_held.Category == ItemCategory.Trash && zone.ZoneName == "TrashCan")
                        matchesHome = true;
                    else if (_held.Category == ItemCategory.Dish && zone.ZoneName == "Sink")
                        matchesHome = true;
                }
                // Proximity-found zone with unpaired pairable — skip the zone,
                // fall through to normal surface placement instead.
                if (matchesHome && !zoneIsDirect)
                {
                    var pairable = _held.GetComponent<PairableItem>();
                    if (pairable != null && pairable.Mode == PairableItem.PairMode.SpecificPartner && !pairable.IsPaired)
                    {
                        zone = null;
                        matchesHome = false;
                    }
                }

                if (matchesHome)
                {
                    _heldRb.constraints = _originalConstraints;
                    _heldRb.linearVelocity = Vector3.zero;

                    if (zone.DestroyOnDeposit)
                    {
                        // Trash can — shrink and destroy
                        zone.RegisterDeposit(_held);
                        ClearHeld();
                        return;
                    }

                    // Auto-slot deposit (shoe rack, etc.) — snap to the next
                    // free slot in a row instead of dropping at the cursor.
                    if (zone.UseSlotting
                        && zone.TryGetNextDepositSlot(out var slotPos, out var slotRot))
                    {
                        _held.OnPlaced(_currentSurface, true, slotPos, slotRot);

                        // Lock slotted items in place — they shouldn't fall off
                        // their slot or roll around. Picking the shoe back up
                        // re-enables physics via PlaceableObject.OnPickedUp.
                        LockRigidbodyAtSlot(_held);

                        zone.RegisterDeposit(_held);
                        OnObjectPlaced?.Invoke(_held);
                        PlayPlaceSFX(_held);
                        ClearHeld();
                        return;
                    }

                    // Normal drop zone — place normally, zone registers deposit
                    // Fall through to standard placement, OnPlaced will set IsAtHome
                }
            }
        }

        // Wall items only on walls, table items only on tables
        if (_currentSurface.IsVertical && !_held.CanWallMount)
        {
            Debug.Log($"[ObjectGrabber] BLOCKED: surface '{_currentSurface.name}' IsVertical={_currentSurface.IsVertical} but item CanWallMount=false");
            return;
        }
        if (!_currentSurface.IsVertical && _held.WallOnly)
        {
            Debug.Log($"[ObjectGrabber] BLOCKED: surface '{_currentSurface.name}' is horizontal but item is WallOnly");
            return;
        }

        // Trash only on floor or trash cans
        if (_held.Category == ItemCategory.Trash)
        {
            var zone = _currentSurface.GetComponent<DropZone>();
            bool isTrashCan = zone != null && zone.DestroyOnDeposit;
            if (!_currentSurface.IsFloor && !isTrashCan)
            {
                Debug.Log($"[ObjectGrabber] BLOCKED TRASH: surface '{_currentSurface.name}' IsFloor={_currentSurface.IsFloor} isTrashCan={isTrashCan}");
                return;
            }
        }

        // Use _grabTarget (cursor-tracked) instead of _heldRb.position for wall face
        // detection — the rigidbody can overshoot through thin wall triggers.
        var hitResult = _currentSurface.ProjectOntoSurface(_grabTarget, cam.transform.position);
        Vector3 pos = _currentSurface.SnapToGrid(hitResult.worldPosition, GetGridSize(_currentSurface), cam.transform.position);

        float halfExtent = GetHeldHalfExtentAlongNormal(hitResult.surfaceNormal);
        pos += hitResult.surfaceNormal * halfExtent;

        Quaternion rot;
        if (_currentSurface.IsVertical)
        {
            rot = Quaternion.LookRotation(hitResult.surfaceNormal, Vector3.up)
                * Quaternion.AngleAxis(_wallRotation, Vector3.forward);
        }
        else
        {
            rot = _held.transform.rotation;
        }

        // Home snap: if placing near the item's home position, use exact home pos/rot
        if (_held.HasHome && Vector3.Distance(pos, _held.HomePosition) < _held.HomeTolerance * 2f)
        {
            pos = _held.HomePosition;
            rot = _held.HomeRotation;
        }

        // Barrier check — reject if placement position overlaps or sits directly
        // above a barrier volume (counter body, furniture interior, etc.).
        // Sphere check catches items placed inside barriers, downward ray catches
        // barriers beneath the surface that the sphere can't reach.
        if (_barrierLayer != 0)
        {
            bool blocked = Physics.CheckSphere(pos, 0.08f, _barrierLayer);
            if (!blocked && !_currentSurface.IsVertical)
            {
                // Probe downward from placement pos — catches barriers inside
                // counter/table bodies that sit just below the surface.
                // Skip for vertical (wall) surfaces — the wall itself is on the
                // barrier layer and the probe would always hit it.
                blocked = Physics.Raycast(pos, Vector3.down, 0.15f, _barrierLayer);
            }
            if (blocked)
            {
                Debug.Log($"[ObjectGrabber] BLOCKED: placement at {pos} is over barrier geometry.");
                return;
            }
        }

        // Cubby capacity check — reject placement if cubby is full
        var capacityCubby = DrawerController.FindByInteriorSurface(_currentSurface);
        if (capacityCubby != null && !capacityCubby.HasInteriorCapacity)
        {
            if (DialoguePortraitBox.Instance != null)
                DialoguePortraitBox.Instance.Say("No room in here.", 2f);
            else
                PickupDescriptionHUD.Instance?.Show("No room in here.");
            return;
        }

        // Occupancy check — block placement if another item already occupies the
        // resolved cell. Pairables stack via the click-on-partner path
        // (TryPairWithClicked above); plain placement here is never allowed to
        // overlap a sibling.
        if (FindOccupant(pos) != null)
        {
            Debug.Log($"[ObjectGrabber] BLOCKED: cell occupied at {pos}");
            return;
        }

        // Restore constraints before placement configures the rigidbody
        _heldRb.constraints = _originalConstraints;
        _heldRb.linearVelocity = Vector3.zero;

        _held.OnPlaced(_currentSurface, true, pos, rot);

        // Book public/private toggle based on placement surface
        var bookItem = _held.GetComponent<BookItem>();
        if (bookItem != null) bookItem.OnBookPlaced(_currentSurface);

        // Cubby privacy: items placed on a closed cubby's interior surface become private.
        // Items placed anywhere else become public (clears stale privacy from previous location).
        var cubbyDrawer = DrawerController.FindByInteriorSurface(_currentSurface);
        bool inClosedCubby = cubbyDrawer != null && cubbyDrawer.IsInteriorAndClosed(_currentSurface);
        var privTag = _held.GetComponent<ReactableTag>();
        if (privTag != null)
            privTag.IsPrivate = inClosedCubby;

        OnObjectPlaced?.Invoke(_held);
        PlayPlaceSFX(_held);

        // DropZone deposit (non-destroy — item stays placed on surface)
        {
            var zone = _currentSurface.GetComponent<DropZone>();
            if (zone != null)
            {
                bool match = (!string.IsNullOrEmpty(_held.HomeZoneName) && zone.ZoneName == _held.HomeZoneName)
                    || (!string.IsNullOrEmpty(_held.AltHomeZoneName) && zone.ZoneName == _held.AltHomeZoneName);
                if (match)
                    zone.RegisterDeposit(_held);
            }
        }

        // Stack-aware plate hooks. No more auto-stack-on-place: stacking only
        // happens through explicit pairable click (TryPairWithClicked above).
        var stackable = _held.GetComponent<StackablePlate>();
        if (stackable != null)
        {
            var dishZone = _currentSurface != null
                ? _currentSurface.GetComponent<DishDropZone>() : null;
            if (dishZone != null)
            {
                // Deposit the held plate plus any child plates in the stack
                dishZone.RegisterDeposit(stackable);
                var childPlates = stackable.GetComponentsInChildren<StackablePlate>();
                foreach (var child in childPlates)
                {
                    if (child != stackable)
                        dishZone.RegisterDeposit(child);
                }
            }
        }

        ClearHeld();
    }

    // ── Pair / stacking helpers ─────────────────────────────────────

    // Forgiving radius for pairing/stacking — SphereCast instead of Raycast
    private const float PairStackRadius = 0.08f;

    [Header("Pair Snap")]
    [Tooltip("World-space radius at which the held item magnetically snaps toward its pair partner while carrying.")]
    [SerializeField] private float _pairSnapRadius = 0.4f;

    [Header("Trash Can Snap")]
    [Tooltip("World-space radius at which trash items start being pulled toward the trash can lid.")]
    [SerializeField] private float _trashSnapRadius = 0.8f;

    [Tooltip("How strongly the item is pulled toward the lid (0 = no pull, 1 = full lock). Interpolated by proximity.")]
    [SerializeField, Range(0f, 1f)] private float _trashSnapStrength = 0.45f;

    [Header("Turntable Snap")]
    [Tooltip("World-space radius at which vinyl items start being pulled toward the turntable platter.")]
    [SerializeField] private float _turntableSnapRadius = 0.6f;

    [Tooltip("How strongly the vinyl is pulled toward the platter (0 = no pull, 1 = full lock).")]
    [SerializeField, Range(0f, 1f)] private float _turntableSnapStrength = 0.5f;

    [Header("Bottle Snap")]
    [Tooltip("World-space radius at which a held bottle snaps toward a glass.")]
    [SerializeField] private float _bottleSnapRadius = 0.6f;

    [Tooltip("How strongly the bottle is pulled toward the glass pour position.")]
    [SerializeField, Range(0f, 1f)] private float _bottleSnapStrength = 0.7f;

    [Header("Watering Can Snap")]
    [Tooltip("World-space radius at which the watering can snaps toward a plant.")]
    [SerializeField] private float _wateringSnapRadius = 1.0f;

    [Tooltip("How strongly the can is pulled toward the plant pour position.")]
    [SerializeField, Range(0f, 1f)] private float _wateringSnapStrength = 0.75f;

    private bool TryPairWithClicked()
    {
        if (_held == null) return false;

        var heldPairable = _held.GetComponent<PairableItem>();
        if (heldPairable == null) return false;
        // SpecificPartner (shoes) can't re-pair, but AnyOfCategory (plates) can stack freely
        if (heldPairable.IsPaired && heldPairable.Mode == PairableItem.PairMode.SpecificPartner) return false;

        Vector2 screenPos = IrisInput.CursorPosition;
        Ray ray = cam.ScreenPointToRay(screenPos);

        // Use SphereCast for forgiving click area, fall back to RaycastAll
        PairableItem clickedPairable = FindComponentAlongRay<PairableItem>(ray, placeableLayer);

        // If precise click missed, accept the snap target we're already locked onto
        if ((clickedPairable == null || clickedPairable == heldPairable || !clickedPairable.CanPairWith(heldPairable))
            && _pairSnapTarget != null && _pairSnapTarget.CanPairWith(heldPairable))
        {
            clickedPairable = _pairSnapTarget;
        }

        if (clickedPairable == null || clickedPairable == heldPairable) return false;
        if (!clickedPairable.CanPairWith(heldPairable)) return false;

        // Release held item from grabber
        _heldRb.constraints = _originalConstraints;
        _heldRb.linearVelocity = Vector3.zero;

        // Clean up held item visuals before pairing
        _held.ForceRestoreMaterial();
        _held.ForceDestroySilhouette();

        // Snap pair
        clickedPairable.SnapPair(heldPairable);

        PlayPlaceSFX(_held);
        ClearHeld();
        return true;
    }

    // ── Pair snap (magnetic carry bias) ──────────────────────────────

    private PairableItem _pairSnapTarget; // currently snapped-to partner (null = no snap)

    /// <summary>
    /// When holding a pairable item near its partner, snap the grab target
    /// to the pair position so the item magnetically locks in place.
    /// Called from UpdateGrabTarget after the normal position is calculated.
    /// </summary>
    private void UpdatePairSnap()
    {
        _pairSnapTarget = null;
        if (_held == null) return;

        var heldPairable = _held.GetComponent<PairableItem>();
        if (heldPairable == null) return;
        if (heldPairable.IsPaired && heldPairable.Mode == PairableItem.PairMode.SpecificPartner) return;

        // Find the nearest valid partner within snap radius
        PairableItem best = null;
        float bestDist = _pairSnapRadius;

        var allItems = PlaceableObject.All;
        for (int i = 0; i < allItems.Count; i++)
        {
            var po = allItems[i];
            if (po == null || po == _held) continue;
            if (po.CurrentState == PlaceableObject.State.Held) continue;

            var pairable = po.GetComponent<PairableItem>();
            if (pairable == null || pairable == heldPairable) continue;
            if (!pairable.CanPairWith(heldPairable)) continue;

            float dist = Vector3.Distance(po.transform.position, _grabTarget);
            if (dist < bestDist)
            {
                bestDist = dist;
                best = pairable;
            }
        }

        if (best == null) return;

        _pairSnapTarget = best;

        // Calculate the position the held item would land at when paired
        Vector3 snapPos = best.GetPairSnapPosition(heldPairable);

        // If on a surface, grid-snap the pair position so items still
        // "click" into the surface grid instead of floating freely.
        if (_currentSurface != null)
            snapPos = _currentSurface.SnapToGrid(snapPos, GetGridSize(_currentSurface), cam.transform.position);

        _grabTarget = snapPos;

        // Hard-teleport so the item locks instantly (no spring lag)
        if (_heldRb != null)
        {
            _heldRb.position = snapPos;
            _heldRb.linearVelocity = Vector3.zero;
            _heldRb.angularVelocity = Vector3.zero;
        }
    }

    // ── Trash can magnetic snap ─────────────────────────────────────

    /// <summary>
    /// When holding a trash item near a trash can, softly pull the grab
    /// target toward the lid to signal "you can drop this here."
    /// </summary>
    private void UpdateTrashCanSnap()
    {
        if (_held == null) return;

        // Only snap items the trash can would accept
        bool isTrash = _held.Category == ItemCategory.Trash
                    || _held.HomeZoneName == "TrashCan"
                    || _held.AltHomeZoneName == "TrashCan";
        if (!isTrash) return;

        // Find nearest trash can within snap radius
        DropZone bestZone = null;
        float bestDist = _trashSnapRadius;

        var allZones = DropZone.All;
        for (int i = 0; i < allZones.Count; i++)
        {
            var zone = allZones[i];
            if (zone == null || !zone.DestroyOnDeposit) continue;
            if (zone.ZoneName != "TrashCan") continue;

            float dist = Vector3.Distance(zone.transform.position, _grabTarget);
            if (dist < bestDist)
            {
                bestDist = dist;
                bestZone = zone;
            }
        }

        if (bestZone == null) return;

        // Pull toward the lid (top of the trash can)
        Vector3 lidPos = bestZone.transform.position + bestZone.transform.up * 0.15f;
        float proximity = 1f - (bestDist / _trashSnapRadius); // 0 at edge, 1 at center
        float strength = proximity * proximity * _trashSnapStrength; // quadratic ease-in
        _grabTarget = Vector3.Lerp(_grabTarget, lidPos, strength);
    }

    // ── Turntable magnetic snap ─────────────────────────────────────

    /// <summary>
    /// When holding a vinyl disc near the turntable, softly pull the grab
    /// target toward the platter to signal "you can place this here."
    /// </summary>
    private void UpdateTurntableSnap()
    {
        if (_held == null) return;
        if (_held.GetComponent<VinylDisc>() == null) return;
        if (RecordSlot.Instance == null) return;

        Vector3 snapPos = RecordSlot.Instance.SnapPoint;
        float dist = Vector3.Distance(snapPos, _grabTarget);
        if (dist > _turntableSnapRadius || dist < 0.01f) return;

        float proximity = 1f - (dist / _turntableSnapRadius);
        float strength = proximity * proximity * _turntableSnapStrength;
        _grabTarget = Vector3.Lerp(_grabTarget, snapPos, strength);
    }

    // ── Watering can magnetic snap + pour trigger ────────────────────

    private WaterablePlant _nearestWaterablePlant;

    /// <summary>
    /// When holding a watering can near a plant, pull toward pour position.
    /// If the player clicks while snapped, start the watering session.
    /// </summary>
    // ── Bottle magnetic snap ────────────────────────────────────────

    private DrinkGlass _nearestDrinkGlass;

    private void UpdateBottleSnap()
    {
        _nearestDrinkGlass = null;
        if (_held == null) return;

        // Only snap bottles toward glasses during the drink-making date phase
        if (DateSessionManager.Instance == null
            || DateSessionManager.Instance.CurrentDatePhase != DateSessionManager.DatePhase.BackgroundJudging)
            return;

        var bottle = _held.GetComponent<BottleItem>();
        if (bottle == null) return;

        // Find nearest DrinkGlass
        DrinkGlass bestGlass = null;
        float bestDist = _bottleSnapRadius;

        foreach (var glass in DrinkGlass.All)
        {
            if (glass == null) continue;
            float dist = Vector3.Distance(glass.transform.position, _grabTarget);
            if (dist < bestDist)
            {
                bestDist = dist;
                bestGlass = glass;
            }
        }

        if (bestGlass == null)
        {
            // Moved away — stop pouring if active
            if (DrinkPourManager.Instance != null
                && DrinkPourManager.Instance.CurrentState == DrinkPourManager.State.Pouring)
                DrinkPourManager.Instance.StopPouring();
            return;
        }

        _nearestDrinkGlass = bestGlass;

        // Snap to pour position above the glass rim
        Vector3 glassTop = bestGlass.transform.position + Vector3.up * 0.15f;
        Vector3 toCursor = _grabTarget - bestGlass.transform.position;
        toCursor.y = 0f;
        if (toCursor.sqrMagnitude < 0.001f) toCursor = Vector3.forward;
        toCursor.Normalize();

        Vector3 pourPos = bestGlass.transform.position + toCursor * 0.08f + Vector3.up * 0.2f;

        float proximity = 1f - (bestDist / _bottleSnapRadius);
        float strength = proximity > 0.4f
            ? Mathf.Lerp(0.5f, 1f, (proximity - 0.4f) / 0.6f)
            : proximity * proximity * _bottleSnapStrength;

        _grabTarget = Vector3.Lerp(_grabTarget, pourPos, strength);

        // Tilt bottle toward glass
        if (proximity > 0.5f)
        {
            Vector3 tiltDir = (bestGlass.transform.position - _held.transform.position).normalized;
            tiltDir.y = 0f;
            float tiltAngle = Mathf.Lerp(0f, 45f, (proximity - 0.5f) / 0.5f);
            Quaternion tiltRot = Quaternion.LookRotation(tiltDir, Vector3.up)
                               * Quaternion.Euler(tiltAngle, 0f, 0f);
            _held.transform.rotation = Quaternion.Slerp(_held.transform.rotation, tiltRot,
                                                         Time.deltaTime * 8f);
        }
    }

    private void UpdateWateringCanSnap()
    {
        _nearestWaterablePlant = null;
        if (_held == null) return;
        if (_held.GetComponent<WateringCan>() == null) return;

        // If we WERE watering but moved away, end the session + dismiss UI
        bool wasWatering = WateringManager.Instance != null
            && WateringManager.Instance.CurrentState == WateringManager.State.Pouring;

        // Find nearest WaterablePlant
        WaterablePlant bestPlant = null;
        float bestDist = _wateringSnapRadius;

        foreach (var plant in WaterablePlant.All)
        {
            if (plant == null) continue;
            float dist = Vector3.Distance(plant.transform.position, _grabTarget);
            if (dist < bestDist)
            {
                bestDist = dist;
                bestPlant = plant;
            }
        }

        if (bestPlant == null)
        {
            // Moved away from all plants — end any active watering session
            if (wasWatering)
                WateringManager.Instance.EndWatering();
            return;
        }

        _nearestWaterablePlant = bestPlant;

        // Snap the can to orbit the plant rim. Mouse left/right rotates
        // the can around the pot. Hard lock when close — the can clicks
        // into position on the rim and waits for the player to hold-click.
        Vector3 plantCenter = bestPlant.transform.position;
        float rimRadius = 0.15f; // distance from plant center to rim edge
        float rimHeight = 0.3f;  // height above plant base (spout above rim)

        // Direction from plant to cursor in XZ
        Vector3 toCursor = _grabTarget - plantCenter;
        toCursor.y = 0f;
        if (toCursor.sqrMagnitude < 0.001f)
            toCursor = Vector3.forward;
        toCursor.Normalize();

        // Pour position orbits the rim
        Vector3 pourPos = plantCenter + toCursor * rimRadius + Vector3.up * rimHeight;

        float proximity = 1f - (bestDist / _wateringSnapRadius);

        // Hard magnetic lock — snaps firmly to the rim, not a soft suggestion
        float strength;
        if (proximity > 0.4f)
            strength = Mathf.Lerp(0.5f, 1f, (proximity - 0.4f) / 0.6f); // strong ramp to full lock
        else
            strength = proximity * proximity * _wateringSnapStrength;

        _grabTarget = Vector3.Lerp(_grabTarget, pourPos, strength);

        // Tilt the 3D watering can to look like it's pouring
        if (_held != null && proximity > 0.5f)
        {
            // Tilt toward the plant center (spout tips inward)
            Vector3 tiltDir = (plantCenter - _held.transform.position).normalized;
            tiltDir.y = 0f;
            float tiltAngle = Mathf.Lerp(0f, 35f, (proximity - 0.5f) / 0.5f); // up to 35° tilt
            Quaternion tiltRot = Quaternion.LookRotation(tiltDir, Vector3.up)
                               * Quaternion.Euler(tiltAngle, 0f, 0f);
            _held.transform.rotation = Quaternion.Slerp(_held.transform.rotation, tiltRot,
                                                         Time.deltaTime * 8f);
        }
    }

    /// <summary>
    /// Forgiving component search along a ray. Tries SphereCast first (wider hit area),
    /// then falls back to RaycastAll for objects the sphere might miss.
    /// </summary>
    private static T FindComponentAlongRay<T>(Ray ray, LayerMask layer) where T : Component
    {
        // 1. SphereCast — generous hit radius
        if (Physics.SphereCast(ray, PairStackRadius, out RaycastHit sphereHit, 100f, layer))
        {
            var comp = sphereHit.collider.GetComponent<T>();
            if (comp == null) comp = sphereHit.collider.GetComponentInParent<T>();
            if (comp != null) return comp;
        }

        // 2. RaycastAll — check all hits along the exact ray
        var hits = Physics.RaycastAll(ray, 100f, layer);
        float bestDist = float.MaxValue;
        T best = null;
        for (int i = 0; i < hits.Length; i++)
        {
            var comp = hits[i].collider.GetComponent<T>();
            if (comp == null) comp = hits[i].collider.GetComponentInParent<T>();
            if (comp != null && hits[i].distance < bestDist)
            {
                bestDist = hits[i].distance;
                best = comp;
            }
        }
        return best;
    }

    /// Double-click while holding a plate with children → detach the topmost child
    /// and place/drop the remaining stack.
    /// </summary>
    private bool TryUnstackHeldPlate()
    {
        var heldStack = _held.GetComponent<StackablePlate>();
        if (heldStack == null) return false;

        // Find topmost child plate
        StackablePlate topChild = null;
        foreach (Transform child in _held.transform)
        {
            var sp = child.GetComponent<StackablePlate>();
            if (sp != null)
                topChild = sp;
        }
        if (topChild == null) return false;

        // Detach the top plate — it becomes the new held object
        topChild.PrepareForGrab();

        // Drop the current stack onto the nearest surface
        _heldRb.constraints = _originalConstraints;
        _heldRb.linearVelocity = Vector3.zero;
        _heldRb.useGravity = true;
        _held.OnDropped();

        // Pick up the detached top plate
        var oldHeld = _held;
        _held = topChild.GetComponent<PlaceableObject>();
        _heldRb = topChild.GetComponent<Rigidbody>();
        if (_heldRb != null)
        {
            _heldRb.useGravity = false;
            _heldRb.isKinematic = false;
            _grabTarget = _heldRb.worldCenterOfMass;
            _originalConstraints = _heldRb.constraints;
            _heldRb.constraints = _originalConstraints | RigidbodyConstraints.FreezeRotation;
        }
        _held.OnPickedUp();

        Debug.Log($"[ObjectGrabber] Unstacked {topChild.name} from {oldHeld.name}");
        return true;
    }

    /// <summary>
    /// Try to deposit the held item at the nearest DropZone when not over a PlacementSurface.
    /// Used for fridge, trash can, etc. that don't have placement surfaces.
    /// </summary>
    private bool TryDepositAtNearbyZone()
    {
        if (_held == null) return false;

        // Raycast to see what we clicked on
        Vector2 screenPos = IrisInput.CursorPosition;
        Ray ray = cam.ScreenPointToRay(screenPos);
        if (!Physics.Raycast(ray, out RaycastHit hit, 100f)) return false;

        // Check the hit object and its parents for a DropZone
        var zone = hit.collider.GetComponent<DropZone>();
        if (zone == null) zone = hit.collider.GetComponentInParent<DropZone>();
        if (zone == null) return false;

        // Check if the held item matches this zone (name match or category match)
        bool matches = (!string.IsNullOrEmpty(_held.HomeZoneName) && zone.ZoneName == _held.HomeZoneName)
                    || (!string.IsNullOrEmpty(_held.AltHomeZoneName) && zone.ZoneName == _held.AltHomeZoneName);
        // Category-specific destroy zones: trash→TrashCan, dishes→Sink
        if (!matches && zone.DestroyOnDeposit)
        {
            if (_held.Category == ItemCategory.Trash && zone.ZoneName == "TrashCan")
                matches = true;
            else if (_held.Category == ItemCategory.Dish && zone.ZoneName == "Sink")
                matches = true;
        }
        if (!matches) return false;

        // Deposit
        _held.ForceRestoreMaterial();
        _held.ForceDestroySilhouette();
        var item = _held;
        ClearHeld();
        zone.RegisterDeposit(item);
        PlayPlaceSFX(item);
        Debug.Log($"[ObjectGrabber] Deposited {item.name} at zone '{zone.ZoneName}'");
        return true;
    }

    private void PlayPlaceSFX(PlaceableObject obj)
    {
        var clip = obj != null && obj.PlaceSFXOverride != null ? obj.PlaceSFXOverride : _placeSFX;
        AudioManager.Instance?.PlaySFX(clip);
    }

    private void ClearHeld()
    {
        // Restore discrete collision detection
        if (_heldRb != null)
            _heldRb.collisionDetectionMode = CollisionDetectionMode.Discrete;

        if (_held != null)
        {
            // Restore normal rendering (undo HeldOnTop shader swap from pickup)
            _held.SetRenderOnTop(false);

            // Always clean up held item visuals
            _held.ForceRestoreMaterial();
            _held.ForceDestroySilhouette();

            // Stop partner highlight flash + restore partner color
            var pairable = _held.GetComponent<PairableItem>();
            if (pairable != null) pairable.OnPutDown();

            // Turn off held highlight
            var hl = _held.GetComponent<InteractableHighlight>();
            if (hl != null)
            {
                hl.SetHighlighted(false);
                hl.SetInteractHighlighted(false);
            }
        }

        _held = null;
        _heldRb = null;
        _currentSurface = null;
        _lastValidSurface = null;
        _isOnWall = false;
        _pairSnapTarget = null;
        ShowShadow(false);
        DestroyGhostPreview();
        ClearPlantHighlights();

        // Safety: unlock cursor in case an interaction lock was active
        GlobalCursorManager.UnlockCursor();

        if (PickupDescriptionHUD.Instance != null)
            PickupDescriptionHUD.Instance.Hide();
    }

    // ── Target highlight blink (generic + plant-specific) ────────────

    /// <summary>Blink a single object's InteractableHighlight N times.</summary>
    private static IEnumerator BlinkHighlight(GameObject target, int blinks)
    {
        if (target == null) yield break;
        var hl = target.GetComponent<InteractableHighlight>();
        if (hl == null) hl = target.AddComponent<InteractableHighlight>();

        for (int b = 0; b < blinks; b++)
        {
            hl.SetHighlighted(true);
            yield return new WaitForSeconds(0.25f);
            hl.SetHighlighted(false);
            yield return new WaitForSeconds(0.2f);
        }
    }


    private Coroutine _plantBlinkRoutine;

    private IEnumerator BlinkPlantHighlights(int blinks)
    {
        var plants = WaterablePlant.All;
        // Ensure each plant has an InteractableHighlight
        for (int i = 0; i < plants.Count; i++)
        {
            if (plants[i] == null) continue;
            if (plants[i].GetComponent<InteractableHighlight>() == null)
                plants[i].gameObject.AddComponent<InteractableHighlight>();
        }

        for (int b = 0; b < blinks; b++)
        {
            // On
            for (int i = 0; i < plants.Count; i++)
            {
                if (plants[i] == null) continue;
                var hl = plants[i].GetComponent<InteractableHighlight>();
                if (hl != null) hl.SetHighlighted(true);
            }
            yield return new WaitForSeconds(0.25f);

            // Off
            for (int i = 0; i < plants.Count; i++)
            {
                if (plants[i] == null) continue;
                var hl = plants[i].GetComponent<InteractableHighlight>();
                if (hl != null) hl.SetHighlighted(false);
            }
            yield return new WaitForSeconds(0.2f);
        }
        _plantBlinkRoutine = null;
    }

    private void ClearPlantHighlights()
    {
        if (_plantBlinkRoutine != null)
        {
            StopCoroutine(_plantBlinkRoutine);
            _plantBlinkRoutine = null;
        }
        var plants = WaterablePlant.All;
        for (int i = 0; i < plants.Count; i++)
        {
            if (plants[i] == null) continue;
            var hl = plants[i].GetComponent<InteractableHighlight>();
            if (hl != null) hl.SetHighlighted(false);
        }
    }

    // ── Grab target (surface raycast with depth-plane fallback) ──────

    private void UpdateGrabTarget()
    {
        Vector2 screenPos = IrisInput.CursorPosition;
        Ray ray = cam.ScreenPointToRay(screenPos);

        bool foundSurface = false;

        // RaycastAll so the ray can pass through nearer surfaces to reach
        // ones further away (e.g. coffee table in living room from kitchen camera).
        var hits = Physics.RaycastAll(ray, 100f, surfaceLayer);
        if (hits.Length == 0 && _held != null)
            Debug.Log($"[UpdateGrabTarget] No surface hits at all. surfaceLayer={surfaceLayer.value}");
        if (hits.Length > 0)
        {
            // Sort nearest-first so we try the camera-closest surface first
            System.Array.Sort(hits, (a, b) => a.distance.CompareTo(b.distance));

            int occlusionMask = _wallLayer | _barrierLayer;
            Vector3 camPos = cam.transform.position;

            for (int h = 0; h < hits.Length; h++)
            {
                var surface = hits[h].collider.GetComponentInParent<PlacementSurface>();
                bool surfaceValid = surface != null
                    && (!surface.IsVertical || _held.CanWallMount)
                    && (surface.IsVertical || !_held.WallOnly);
                if (!surfaceValid)
                {
                    Debug.Log($"[UpdateGrabTarget] Skipped {hits[h].collider.name}: surface={surface?.name}, isVertical={surface?.IsVertical}, canWallMount={_held?.CanWallMount}, wallOnly={_held?.WallOnly}");
                    continue;
                }

                // Project onto the actual surface face to get the real placement point
                var hitResult = surface.ProjectOntoSurface(hits[h].point, camPos);
                Vector3 projectedPos = hitResult.worldPosition;

                // Occlusion check: reject surfaces whose placement point is
                // hidden behind solid geometry (counter, bookshelf, etc.).
                // Skip for floor surfaces — floor placement should never be
                // blocked by furniture the camera looks through.
                if (!surface.IsFloor)
                {
                    Vector3 toProj = projectedPos - camPos;
                    float projDist = toProj.magnitude;
                    if (projDist > 0.1f)
                    {
                        Vector3 projDir = toProj / projDist;
                        if (Physics.Raycast(camPos, projDir, out RaycastHit occHit,
                                projDist - 0.05f, occlusionMask))
                        {
                            // Allow if the blocker is the surface's own furniture
                            bool sameFurniture = occHit.transform.IsChildOf(surface.transform)
                                              || surface.transform.IsChildOf(occHit.transform);
                            // Allow if the hit is very close to the surface — it's
                            // the surface's own supporting geometry (floor slab,
                            // table top mesh, etc.), not a separate occluder.
                            bool nearSurface = Vector3.Distance(occHit.point, projectedPos) < 0.15f;
                            if (!sameFurniture && !nearSurface) continue; // truly occluded — skip
                        }
                    }
                }

                // This surface is valid and visible — use it
                _currentSurface = surface;
                _lastValidSurface = surface;
                _isOnWall = surface.IsVertical;

                Vector3 pos = surface.SnapToGrid(hitResult.worldPosition, GetGridSize(surface), camPos);

                float halfExtent = GetHeldHalfExtentAlongNormal(hitResult.surfaceNormal);
                pos += hitResult.surfaceNormal * halfExtent;

                // Heavy slot snap — if the surface has a slotted DropZone the
                // held item belongs to, override pos with the next free slot
                // and teleport the rigidbody so the shoe physically clicks in.
                var slotZone = surface.GetComponent<DropZone>();
                if (slotZone == null) slotZone = surface.GetComponentInParent<DropZone>();
                if (slotZone != null && slotZone.UseSlotting && _held != null
                    && (slotZone.ZoneName == _held.HomeZoneName || slotZone.ZoneName == _held.AltHomeZoneName)
                    && slotZone.TryPeekNextDepositSlot(out var slotPos, out _))
                {
                    pos = slotPos;
                    if (_heldRb != null)
                    {
                        _heldRb.position = pos;
                        _heldRb.linearVelocity = Vector3.zero;
                        _heldRb.angularVelocity = Vector3.zero;
                    }
                }

                _grabTarget = pos;

                // Track depth so fallback stays smooth if cursor leaves surface
                _fallbackDepth = Vector3.Dot(
                    _grabTarget - camPos,
                    cam.transform.forward);

                if (_isOnWall)
                    _held.AlignToWall(hitResult.surfaceNormal, _wallRotation);

                foundSurface = true;
                break; // first valid, non-occluded surface wins
            }
        }

        if (!foundSurface)
        {
            // No valid surface or dollying — float at fallback depth following cursor
            _currentSurface = null;
            _isOnWall = false;

            Vector3 planePoint = cam.transform.position + cam.transform.forward * _fallbackDepth;
            var plane = new Plane(-cam.transform.forward, planePoint);
            if (plane.Raycast(ray, out float enter))
                _grabTarget = ray.GetPoint(enter);
        }

        // Wall clamping removed — felt too harsh. Surface bounds still constrain placement.

        // Pair snap: if holding a pairable item near its partner, override
        // _grabTarget to magnetically lock onto the pair position.
        UpdatePairSnap();

        // Trash can snap: soft pull toward lid when carrying trash nearby.
        UpdateTrashCanSnap();

        // Turntable snap: soft pull toward platter when carrying vinyl nearby.
        UpdateTurntableSnap();

        // Watering can snap: pull toward nearest plant when carrying the can.
        UpdateWateringCanSnap();

        // Bottle snap: pull toward nearest drink glass when carrying a bottle.
        UpdateBottleSnap();
    }

    /// <summary>
    /// Clamps _grabTarget so the held item cannot pass through walls and always
    /// stays on the camera's side of any geometry (no wall between camera and item).
    /// </summary>
    private void ClampGrabTargetToWalls()
    {
        if (_heldRb == null) return;
        // Only clamp against explicit barrier cubes — not general wall geometry,
        // which catches the entire room and makes carrying feel sticky.
        if (_barrierLayer == 0) return;

        const float margin = 0.05f;
        int blockMask = _barrierLayer;

        // 1) Camera → target: keep item on camera's side of any wall/barrier
        //    (skip when on a surface to allow cross-room placement)
        if (_currentSurface == null)
        {
            Vector3 camPos = cam.transform.position;
            Vector3 camToTarget = _grabTarget - camPos;
            float camDist = camToTarget.magnitude;

            if (camDist > 0.001f &&
                Physics.Raycast(camPos, camToTarget.normalized, out RaycastHit camHit, camDist, blockMask))
            {
                float safeDist = Mathf.Max(0f, camHit.distance - margin);
                _grabTarget = camPos + camToTarget.normalized * safeDist;
            }
        }

        // 2) Current position → target: prevent tunneling through walls/barriers
        //    (always active — even when snapped to a surface)
        Vector3 from = _heldRb.position;
        Vector3 delta = _grabTarget - from;
        float dist = delta.magnitude;

        if (dist > 0.001f &&
            Physics.Raycast(from, delta.normalized, out RaycastHit wallHit, dist, blockMask))
        {
            float safeDist = Mathf.Max(0f, wallHit.distance - margin);
            _grabTarget = from + delta.normalized * safeDist;
        }
    }

    // ── Rotate input ────────────────────────────────────────────────
    // RMB          = roll (Z axis)
    // Mouse Fwd(4) = yaw  (Y axis)
    // Mouse Back(3)= flip (X axis — toggle upright/flat)

    private void UpdateScrollInput()
    {
        var mouse = UnityEngine.InputSystem.Mouse.current;

        // RMB = roll around Z
        bool rollPressed = mouse != null && mouse.rightButton.wasPressedThisFrame;
        if (rollPressed && _held.AllowRoll)
        {
            float angle = scrollRotateStep;
            _held.transform.Rotate(0f, 0f, angle, Space.Self);
        }

        // Mouse Forward (4) = yaw around Y
        bool yawPressed = Input.GetMouseButtonDown(4);
        if (!yawPressed
            && UnityEngine.InputSystem.Gamepad.current != null
            && UnityEngine.InputSystem.Gamepad.current.rightShoulder.wasPressedThisFrame)
            yawPressed = true;

        if (yawPressed && _held.AllowYaw)
        {
            float angle = scrollRotateStep;
            if (_isOnWall)
                _wallRotation += angle;
            else
                _held.transform.Rotate(0f, angle, 0f, Space.World);
        }

        // Mouse Back (3) = flip around X (toggle upright/flat)
        bool flipPressed = Input.GetMouseButtonDown(3);

        if (flipPressed && _held.AllowFlip)
        {
            Vector3 euler = _held.transform.eulerAngles;
            float xAngle = Mathf.DeltaAngle(euler.x, 0f);
            bool isUpright = Mathf.Abs(xAngle) < 45f;

            if (isUpright)
                _held.transform.Rotate(90f, 0f, 0f, Space.Self); // lay flat
            else
                _held.transform.rotation = Quaternion.Euler(0f, euler.y, 0f); // stand up
        }
    }

    // ── Helper: half-extent along a normal ────────────────────────────

    private const float PlacementSafetyMargin = 0.02f;

    private float GetHeldHalfExtentAlongNormal(Vector3 normal)
    {
        // Use cached extents (colliders are disabled while held)
        return Mathf.Abs(Vector3.Dot(_heldBoundsExtents, normal.normalized)) + PlacementSafetyMargin;
    }

    /// <summary>
    /// Lock a slot-deposited item (and any paired children) so it can't fall
    /// out of the slot or get bumped around. Reverted on next pickup via
    /// PlaceableObject.OnPickedUp, which sets isKinematic = false.
    /// </summary>
    private static void LockRigidbodyAtSlot(PlaceableObject po)
    {
        if (po == null) return;

        var rb = po.GetComponent<Rigidbody>();
        if (rb != null)
        {
            rb.linearVelocity = Vector3.zero;
            rb.angularVelocity = Vector3.zero;
            rb.isKinematic = true;
            rb.useGravity = false;
        }

        // Paired partner is parented under this transform — lock it too.
        var childRbs = po.GetComponentsInChildren<Rigidbody>();
        for (int i = 0; i < childRbs.Length; i++)
        {
            if (childRbs[i] == rb) continue;
            childRbs[i].linearVelocity = Vector3.zero;
            childRbs[i].angularVelocity = Vector3.zero;
            childRbs[i].isKinematic = true;
            childRbs[i].useGravity = false;
        }
    }

    // Buffer reused by FindOccupant — keeps the helper allocation-free.
    private static readonly Collider[] s_occupancyBuffer = new Collider[16];

    /// <summary>
    /// Returns a PlaceableObject occupying the cell at <paramref name="worldPos"/>
    /// for the held item, or null if the cell is free. Excludes the held item itself
    /// and any of its children. Used for placement gating and shadow color.
    /// </summary>
    private PlaceableObject FindOccupant(Vector3 worldPos)
    {
        if (_held == null) return null;

        // For wall items: use the tangent-plane extents (X and Y in wall space)
        // which are larger than the thin Z depth. This prevents wall items from
        // overlapping each other on the same wall.
        float radius;
        if (_isOnWall)
        {
            radius = Mathf.Max(_heldBoundsExtents.x, _heldBoundsExtents.y) * 0.8f;
            if (radius < 0.04f) radius = 0.04f;
        }
        else
        {
            radius = Mathf.Max(_heldBoundsExtents.x, _heldBoundsExtents.z) * 0.85f;
            if (radius < 0.02f) radius = 0.02f;
        }

        int count = Physics.OverlapSphereNonAlloc(worldPos, radius, s_occupancyBuffer, placeableLayer, QueryTriggerInteraction.Ignore);
        for (int i = 0; i < count; i++)
        {
            var po = s_occupancyBuffer[i].GetComponentInParent<PlaceableObject>();
            if (po == null) continue;
            if (po == _held) continue;
            if (po.transform.IsChildOf(_held.transform)) continue;
            return po;
        }
        return null;
    }

    // ── Shadow preview ──────────────────────────────────────────────

    private void BuildShadow()
    {
        _shadowGO = new GameObject("PlacementShadow");
        _shadowGO.transform.SetParent(transform);

        var mf = _shadowGO.AddComponent<MeshFilter>();
        _shadowRenderer = _shadowGO.AddComponent<MeshRenderer>();

        var mesh = new Mesh { name = "ShadowQuad" };
        mesh.vertices = new[]
        {
            new Vector3(-0.5f, 0f, -0.5f),
            new Vector3( 0.5f, 0f, -0.5f),
            new Vector3( 0.5f, 0f,  0.5f),
            new Vector3(-0.5f, 0f,  0.5f)
        };
        mesh.uv = new[]
        {
            new Vector2(0f, 0f), new Vector2(1f, 0f),
            new Vector2(1f, 1f), new Vector2(0f, 1f)
        };
        mesh.triangles = new[] { 0, 2, 1, 0, 3, 2 };
        mesh.RecalculateNormals();
        mf.sharedMesh = mesh;

        int texSize = 32;
        var tex = new Texture2D(texSize, texSize, TextureFormat.RGBA32, false);
        tex.filterMode = FilterMode.Bilinear;
        tex.wrapMode = TextureWrapMode.Clamp;
        float center = texSize * 0.5f;
        float radius = center - 1f;
        for (int y = 0; y < texSize; y++)
        {
            for (int x = 0; x < texSize; x++)
            {
                float dist = Vector2.Distance(new Vector2(x, y), new Vector2(center, center));
                float a = Mathf.Clamp01((radius - dist) / 2f);
                tex.SetPixel(x, y, new Color(1f, 1f, 1f, a));
            }
        }
        tex.Apply();

        var shader = Shader.Find("Universal Render Pipeline/Particles/Unlit");
        if (shader == null) shader = Shader.Find("Sprites/Default");
        if (shader == null) shader = Shader.Find("Unlit/Transparent");
        _shadowMat = new Material(shader);
        _shadowMat.mainTexture = tex;
        _shadowMat.color = s_shadowValid;
        _shadowMat.SetFloat("_Surface", 1f);
        _shadowMat.SetFloat("_Blend", 0f);
        _shadowMat.SetInt("_ZTest", (int)CompareFunction.Always);
        _shadowMat.renderQueue = 3900;
        _shadowRenderer.sharedMaterial = _shadowMat;
        _shadowRenderer.shadowCastingMode = ShadowCastingMode.Off;
        _shadowRenderer.receiveShadows = false;

        _shadowGO.SetActive(false);
    }

    private void ShowShadow(bool show)
    {
        if (_shadowGO != null)
            _shadowGO.SetActive(show);
    }

    // ── Ghost preview ──────────────────────────────────────────────

    /// <summary>
    /// Build a translucent clone of the held item, reparented under a ghost
    /// root so we can move it to the grid-snapped position each frame. The
    /// player sees exactly where the real item will land without breaking the
    /// smooth carry motion of the held item itself.
    /// </summary>
    private void BuildGhostPreview(PlaceableObject source)
    {
        if (!_useGhostPreview || source == null) return;
        DestroyGhostPreview();

        _ghostPreviewGO = Instantiate(source.gameObject);
        _ghostPreviewGO.name = $"GhostPreview_{source.name}";
        _ghostPreviewGO.transform.localScale = source.transform.lossyScale;

        // Strip everything that isn't a pure visual (transform + mesh render).
        // Destroy RequireComponent owners first (PlaceableObject → Rigidbody/Collider
        // dependency) so their dependencies can be removed in the second pass.
        foreach (var po in _ghostPreviewGO.GetComponentsInChildren<PlaceableObject>(true))
            DestroyImmediate(po);
        foreach (var pi in _ghostPreviewGO.GetComponentsInChildren<PairableItem>(true))
            DestroyImmediate(pi);

        var comps = _ghostPreviewGO.GetComponentsInChildren<Component>(includeInactive: true);
        for (int i = 0; i < comps.Length; i++)
        {
            var c = comps[i];
            if (c == null) continue;
            if (c is Transform) continue;
            if (c is MeshFilter) continue;
            if (c is MeshRenderer) continue;
            Destroy(c);
        }

        // Force every layer to IgnoreRaycast so the ghost never catches
        // cursor raycasts, occupancy checks, or placement surface hits.
        int ignoreLayer = 2; // built-in IgnoreRaycast
        foreach (Transform t in _ghostPreviewGO.GetComponentsInChildren<Transform>(true))
            t.gameObject.layer = ignoreLayer;

        // Replace materials with a translucent tint version so the ghost looks
        // like a semi-see-through preview instead of a solid duplicate.
        _ghostPreviewMats.Clear();
        var ghostShader = Shader.Find("Universal Render Pipeline/Particles/Unlit");
        if (ghostShader == null) ghostShader = Shader.Find("Sprites/Default");
        var renderers = _ghostPreviewGO.GetComponentsInChildren<Renderer>(includeInactive: true);
        for (int i = 0; i < renderers.Length; i++)
        {
            var r = renderers[i];
            if (r == null) continue;
            var mat = new Material(ghostShader);
            mat.SetFloat("_Surface", 1f);
            mat.SetFloat("_Blend", 0f);
            mat.SetFloat("_ZWrite", 0f);
            mat.SetOverrideTag("RenderType", "Transparent");
            mat.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");
            mat.renderQueue = 3100;
            mat.color = _ghostTint;
            r.sharedMaterial = mat;
            r.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            r.receiveShadows = false;
            _ghostPreviewMats.Add(mat);
        }

        _ghostPreviewGO.SetActive(false); // hidden until UpdateShadow positions it
    }

    /// <summary>Position the ghost at the currently-planned placement pose.
    /// When visible, tints green (valid) or red (can't fit / blocked).</summary>
    private void UpdateGhostPreview(Vector3 worldPos, Quaternion worldRot, bool show, bool valid = true)
    {
        if (_ghostPreviewGO == null) return;
        if (show)
        {
            _ghostPreviewGO.transform.SetPositionAndRotation(worldPos, worldRot);
            if (!_ghostPreviewGO.activeSelf)
                _ghostPreviewGO.SetActive(true);

            // Tint ghost based on placement validity
            Color tint = valid ? _ghostTint : _ghostTintInvalid;
            for (int i = 0; i < _ghostPreviewMats.Count; i++)
                if (_ghostPreviewMats[i] != null) _ghostPreviewMats[i].color = tint;
        }
        else if (_ghostPreviewGO.activeSelf)
        {
            _ghostPreviewGO.SetActive(false);
        }
    }

    private void DestroyGhostPreview()
    {
        for (int i = 0; i < _ghostPreviewMats.Count; i++)
            if (_ghostPreviewMats[i] != null) Destroy(_ghostPreviewMats[i]);
        _ghostPreviewMats.Clear();

        if (_ghostPreviewGO != null)
        {
            Destroy(_ghostPreviewGO);
            _ghostPreviewGO = null;
        }
    }

    private void UpdateShadow()
    {
        if (_shadowGO == null || _heldRb == null) return;

        // Hide shadow and ghost while magnetically snapped to an interaction
        // target (bottle→glass, watering can→plant, shoe→partner) — the snap
        // itself is the visual feedback, not the placement preview
        if (_nearestDrinkGlass != null || _nearestWaterablePlant != null || _pairSnapTarget != null)
        {
            _shadowGO.SetActive(false);
            UpdateGhostPreview(Vector3.zero, Quaternion.identity, show: false);
            return;
        }

        // Only show shadow when hovering a valid placement surface
        if (_currentSurface == null)
        {
            _shadowGO.SetActive(false);
            UpdateGhostPreview(Vector3.zero, Quaternion.identity, show: false);
            return;
        }

        _shadowGO.SetActive(true);

        var hitResult = _currentSurface.ProjectOntoSurface(_grabTarget, cam.transform.position);

        // Slot-zone fast path: if the surface has a slotted DropZone the held
        // item belongs to, the shadow follows the slot — not the cursor — and
        // is green whenever the rack has any free slot. The actual click goes
        // through the auto-slot deposit, which doesn't care about grid cells.
        var slotZone = _currentSurface.GetComponent<DropZone>();
        if (slotZone == null) slotZone = _currentSurface.GetComponentInParent<DropZone>();
        bool isSlotZoneMatch = slotZone != null && slotZone.UseSlotting && _held != null
            && (slotZone.ZoneName == _held.HomeZoneName || slotZone.ZoneName == _held.AltHomeZoneName);

        if (isSlotZoneMatch)
        {
            bool slotFree = slotZone.TryPeekNextDepositSlot(out Vector3 slotPos, out Quaternion slotRot);
            Vector3 slotShadow = slotFree
                ? slotPos + hitResult.surfaceNormal * 0.01f
                : hitResult.worldPosition + hitResult.surfaceNormal * 0.01f;

            _shadowMat.color = slotFree ? s_shadowValid : s_shadowInvalid;
            _shadowGO.transform.position = slotShadow;
            _shadowGO.transform.rotation = Quaternion.FromToRotation(Vector3.up, hitResult.surfaceNormal);
            _shadowGO.transform.localScale = new Vector3(_heldShadowDiameter, 1f, _heldShadowDiameter);

            // Ghost preview follows the slot pose — red if rack is full.
            UpdateGhostPreview(slotFree ? slotPos : hitResult.worldPosition,
                               slotFree ? slotRot : Quaternion.identity,
                               show: true, valid: slotFree);
            return;
        }

        // Snap the preview to the same grid cell Place() will use, so what you
        // see is exactly what you'll get.
        Vector3 snapped = _currentSurface.SnapToGrid(hitResult.worldPosition, GetGridSize(_currentSurface), cam.transform.position);
        float halfExtent = GetHeldHalfExtentAlongNormal(hitResult.surfaceNormal);
        Vector3 placePos = snapped + hitResult.surfaceNormal * halfExtent;

        Quaternion placeRot = _currentSurface.IsVertical
            ? Quaternion.LookRotation(hitResult.surfaceNormal, Vector3.up)
              * Quaternion.AngleAxis(_wallRotation, Vector3.forward)
            : _held.transform.rotation;

        // Mirror the home-snap override from Place() so ghost matches exactly
        if (_held.HasHome && Vector3.Distance(placePos, _held.HomePosition) < _held.HomeTolerance * 2f)
        {
            placePos = _held.HomePosition;
            placeRot = _held.HomeRotation;
        }

        // Shadow always sits directly under the ghost on the surface face.
        // Derived from placePos so any override (home snap, etc.) keeps them aligned.
        Vector3 shadowPos = placePos - hitResult.surfaceNormal * (halfExtent - 0.01f);
        Quaternion shadowRot = Quaternion.FromToRotation(Vector3.up, hitResult.surfaceNormal);

        bool canPlace = (!_currentSurface.IsVertical || _held.CanWallMount)
            && (_currentSurface.IsVertical || !_held.WallOnly);

        // Trash items only show valid on floor surfaces and trash cans
        if (canPlace && _held.Category == ItemCategory.Trash)
        {
            var zone = _currentSurface.GetComponent<DropZone>();
            bool isTrashCan = zone != null && zone.DestroyOnDeposit;
            canPlace = _currentSurface.IsFloor || isTrashCan;
        }

        // Barrier: blocked if placement sits over barrier geometry
        if (canPlace && _barrierLayer != 0)
        {
            bool overBarrier = Physics.CheckSphere(placePos, 0.08f, _barrierLayer);
            if (!overBarrier && !_currentSurface.IsVertical)
                overBarrier = Physics.Raycast(placePos, Vector3.down, 0.15f, _barrierLayer);
            if (overBarrier) canPlace = false;
        }

        // Occupancy: blocked unless the occupant is a valid pair partner of the held item.
        if (canPlace)
        {
            var occupant = FindOccupant(placePos);
            if (occupant != null)
            {
                var heldPair = _held.GetComponent<PairableItem>();
                var occPair = occupant.GetComponent<PairableItem>();
                bool canStackHere = heldPair != null && occPair != null
                    && occPair.CanPairWith(heldPair);
                if (!canStackHere) canPlace = false;
            }
        }

        _shadowMat.color = canPlace ? s_shadowValid : s_shadowInvalid;
        _shadowGO.transform.position = shadowPos;
        _shadowGO.transform.rotation = shadowRot;
        _shadowGO.transform.localScale = new Vector3(_heldShadowDiameter, 1f, _heldShadowDiameter);

        // Ghost preview sits at the planned landing pose — green when valid,
        // red when the item can't fit or placement is blocked.
        UpdateGhostPreview(placePos, placeRot, show: true, valid: canPlace);
    }

    // ── Public API ──────────────────────────────────────────────────

    /// <summary>
    /// Enable or disable grabbing. Called by ApartmentManager during state transitions.
    /// When disabled while holding, forces a drop onto the nearest surface.
    /// </summary>
    public void SetEnabled(bool enabled)
    {
        _isEnabled = enabled;

        if (!enabled && _held != null)
        {
            // Restore rotation constraints before configuring rigidbody
            _heldRb.constraints = _originalConstraints;

            var nearest = FindNearestSurfaceForHeld(_heldRb.position);
            if (nearest != null)
            {
                var hitResult = nearest.ProjectOntoSurface(_heldRb.position, cam != null ? cam.transform.position : (Vector3?)null);
                float halfExtent = GetHeldHalfExtentAlongNormal(hitResult.surfaceNormal);
                Vector3 pos = hitResult.worldPosition + hitResult.surfaceNormal * halfExtent;
                Quaternion rot = nearest.IsVertical
                    ? Quaternion.LookRotation(hitResult.surfaceNormal, Vector3.up)
                    : _held.transform.rotation;

                _heldRb.linearVelocity = Vector3.zero;
                _held.OnPlaced(nearest, false, pos, rot);

                // Book public/private toggle on force-drop
                var bookItem = _held.GetComponent<BookItem>();
                if (bookItem != null) bookItem.OnBookPlaced(nearest);

                // Stack-aware plate hooks on force-drop. Auto-stack-on-place
                // is gone — pairing is the only stack path now.
                var stackable = _held.GetComponent<StackablePlate>();
                if (stackable != null)
                {
                    var dropZone = nearest.GetComponent<DishDropZone>();
                    if (dropZone != null)
                    {
                        dropZone.RegisterDeposit(stackable);
                        var childPlates = stackable.GetComponentsInChildren<StackablePlate>();
                        foreach (var child in childPlates)
                        {
                            if (child != stackable)
                                dropZone.RegisterDeposit(child);
                        }
                    }
                }
            }
            else
            {
                _heldRb.useGravity = true;
                _heldRb.linearVelocity = Vector3.zero;
                _held.OnDropped();
            }

            ClearHeld();
        }
    }

    private PlacementSurface FindNearestSurfaceForHeld(Vector3 worldPos)
    {
        if (_held == null) return PlacementSurface.FindNearest(worldPos);
        return PlacementSurface.FindNearest(worldPos,
            skipVertical: !_held.CanWallMount,
            skipHorizontal: _held.WallOnly);
    }
}
